/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { auditsAcceptInformationRequestEvidence } from "../funcs/auditsAcceptInformationRequestEvidence.js";
import { auditsCreateCommentForEvidence } from "../funcs/auditsCreateCommentForEvidence.js";
import { auditsCreateCommentForInformationRequest } from "../funcs/auditsCreateCommentForInformationRequest.js";
import { auditsCreateCustomControl } from "../funcs/auditsCreateCustomControl.js";
import { auditsCreateCustomEvidenceRequest } from "../funcs/auditsCreateCustomEvidenceRequest.js";
import { auditsCreateInformationRequest } from "../funcs/auditsCreateInformationRequest.js";
import { auditsDeleteCommentForInformationRequest } from "../funcs/auditsDeleteCommentForInformationRequest.js";
import { auditsDeleteInformationRequest } from "../funcs/auditsDeleteInformationRequest.js";
import { auditsFlagInformationRequestEvidence } from "../funcs/auditsFlagInformationRequestEvidence.js";
import { auditsGetAudit } from "../funcs/auditsGetAudit.js";
import { auditsGetEvidenceUrls } from "../funcs/auditsGetEvidenceUrls.js";
import { auditsGetFrameworkCodes } from "../funcs/auditsGetFrameworkCodes.js";
import { auditsGetInformationRequest } from "../funcs/auditsGetInformationRequest.js";
import { auditsGetInformationRequestTestSnapshotEvidenceDetail } from "../funcs/auditsGetInformationRequestTestSnapshotEvidenceDetail.js";
import { auditsGetVulnerableAssets } from "../funcs/auditsGetVulnerableAssets.js";
import { auditsList } from "../funcs/auditsList.js";
import { auditsListAccountAccessServices } from "../funcs/auditsListAccountAccessServices.js";
import { auditsListAuditIssues } from "../funcs/auditsListAuditIssues.js";
import { auditsListAuditRisks } from "../funcs/auditsListAuditRisks.js";
import { auditsListAuditSnapshots } from "../funcs/auditsListAuditSnapshots.js";
import { auditsListCodeChanges } from "../funcs/auditsListCodeChanges.js";
import { auditsListComments } from "../funcs/auditsListComments.js";
import { auditsListCommentsForInformationRequest } from "../funcs/auditsListCommentsForInformationRequest.js";
import { auditsListControls } from "../funcs/auditsListControls.js";
import { auditsListEvidence } from "../funcs/auditsListEvidence.js";
import { auditsListInformationRequestActivity } from "../funcs/auditsListInformationRequestActivity.js";
import { auditsListInformationRequestEvidence } from "../funcs/auditsListInformationRequestEvidence.js";
import { auditsListInformationRequests } from "../funcs/auditsListInformationRequests.js";
import { auditsListInformationRequestsForControl } from "../funcs/auditsListInformationRequestsForControl.js";
import { auditsListMonitoredComputersInAuditScope } from "../funcs/auditsListMonitoredComputersInAuditScope.js";
import { auditsListPeopleInAuditScope } from "../funcs/auditsListPeopleInAuditScope.js";
import { auditsListPersonnelAccountAccess } from "../funcs/auditsListPersonnelAccountAccess.js";
import { auditsListPersonnelGroups } from "../funcs/auditsListPersonnelGroups.js";
import { auditsListPersonnelPeople } from "../funcs/auditsListPersonnelPeople.js";
import { auditsListRiskSnapshots } from "../funcs/auditsListRiskSnapshots.js";
import { auditsListVendors } from "../funcs/auditsListVendors.js";
import { auditsListVendorsInAuditScope } from "../funcs/auditsListVendorsInAuditScope.js";
import { auditsListVulnerabilities } from "../funcs/auditsListVulnerabilities.js";
import { auditsListVulnerabilityRemediationsInAuditScope } from "../funcs/auditsListVulnerabilityRemediationsInAuditScope.js";
import { auditsShareInformationRequestList } from "../funcs/auditsShareInformationRequestList.js";
import { auditsUpdateCommentForInformationRequest } from "../funcs/auditsUpdateCommentForInformationRequest.js";
import { auditsUpdateEvidence } from "../funcs/auditsUpdateEvidence.js";
import { auditsUpdateInformationRequest } from "../funcs/auditsUpdateInformationRequest.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Audits extends ClientSDK {
  /**
   * List audits
   *
   * @remarks
   * Returns a paginated list of audits scoped to the audit firm.
   *
   * To identify IRL (Information Request List) audits, check for the presence of the
   * `auditorRequestListMetadata` field. This field is only present for IRL-based audits
   * and will be `undefined` for standard audits.
   *
   * Rate limit: 250 requests / minute.
   */
  async list(
    request: operations.ListAuditsRequest,
    options?: RequestOptions,
  ): Promise<components.PaginatedResponseAudit> {
    return unwrapAsync(auditsList(
      this,
      request,
      options,
    ));
  }

  /**
   * Get audit by ID
   *
   * @remarks
   * Returns a single audit by ID, scoped to the audit firm.
   *
   * To identify IRL (Information Request List) audits, check for the presence of the
   * `auditorRequestListMetadata` field. This field is only present for IRL-based audits
   * and will be `undefined` for standard audits.
   *
   * Rate limit: 250 requests / minute.
   */
  async getAudit(
    request: operations.GetAuditRequest,
    options?: RequestOptions,
  ): Promise<components.Audit> {
    return unwrapAsync(auditsGetAudit(
      this,
      request,
      options,
    ));
  }

  /**
   * List code changes for an audit
   *
   * @remarks
   * Retrieves code changes population data for an audit.
   *
   * This endpoint provides access to code change records (pull requests)
   * visible to auditors during an audit engagement.
   *
   * Supports filtering by:
   * - `search`: Searches code change titles and repository names (case-insensitive)
   * - `sourcesMatchesAny`: Filters by version control source (accepted values: github, gitlab, bitbucket, azuredevops)
   * - `closedAfterDate` / `closedBeforeDate`: Filters by the closed date range
   *
   * Uses cursor-based pagination. To paginate:
   * 1. Make initial request with desired `pageSize`
   * 2. Check `results.pageInfo.hasNextPage`
   * 3. Use `results.pageInfo.endCursor` as `pageCursor` for next request
   *
   * Results are sorted by closed date (newest first). This sort order is
   * fixed and cannot be customized via query parameters.
   *
   * Rate limit: 10 requests / minute.
   */
  async listCodeChanges(
    request: operations.ListCodeChangesRequest,
    options?: RequestOptions,
  ): Promise<components.PaginatedResponseCodeChange> {
    return unwrapAsync(auditsListCodeChanges(
      this,
      request,
      options,
    ));
  }

  /**
   * List audit comments
   *
   * @remarks
   * Returns a paginated list of comments for an audit.
   *
   * Rate limit: 250 requests / minute.
   */
  async listComments(
    request: operations.ListAuditCommentsRequest,
    options?: RequestOptions,
  ): Promise<components.PaginatedResponseComment> {
    return unwrapAsync(auditsListComments(
      this,
      request,
      options,
    ));
  }

  /**
   * List audit controls
   *
   * @remarks
   * Returns a paginated list of controls for an audit.
   *
   * Rate limit: 250 requests / minute.
   */
  async listControls(
    request: operations.ListAuditControlsRequest,
    options?: RequestOptions,
  ): Promise<components.PaginatedResponseAuditorControl> {
    return unwrapAsync(auditsListControls(
      this,
      request,
      options,
    ));
  }

  /**
   * Create a custom control for an audit
   *
   * @remarks
   * Create a custom control for an audit.
   *
   * Rate limit: 10 requests / minute.
   */
  async createCustomControl(
    request: operations.CreateCustomControlRequest,
    options?: RequestOptions,
  ): Promise<components.Control> {
    return unwrapAsync(auditsCreateCustomControl(
      this,
      request,
      options,
    ));
  }

  /**
   * List information requests linked to a control within an audit
   *
   * @remarks
   * Returns a paginated list of active information requests linked to a specific
   * control within an IRL audit. An information request is linked to a control
   * either via its framework codes (`criteriaIds`) or via a direct association
   * (`additionalControlIds`).
   *
   * Soft-deleted information requests are not included in the response. To
   * synchronize deletions, use `GET /audits/{auditId}/information-requests`,
   * which supports `changedSinceDate` and includes soft-deleted records.
   *
   * Returns 404 when the control is not part of the audit. Returns an empty page
   * when the control is part of the audit but has no active IRLs linked to it.
   *
   * Pagination usage:
   * 1. Make initial request with desired `pageSize`
   * 2. Check `results.pageInfo.hasNextPage` to see if more data exists
   * 3. If true, use `results.pageInfo.endCursor` as `pageCursor` in next request
   * 4. Repeat until `hasNextPage` is false
   *
   * Rate limit: 50 requests / minute.
   */
  async listInformationRequestsForControl(
    request: operations.ListInformationRequestsForControlRequest,
    options?: RequestOptions,
  ): Promise<components.PaginatedResponseInformationRequest> {
    return unwrapAsync(auditsListInformationRequestsForControl(
      this,
      request,
      options,
    ));
  }

  /**
   * List audit evidence
   *
   * @remarks
   * Returns a paginated list of evidence for an audit.
   *
   * Rate limit: 250 requests / minute.
   */
  async listEvidence(
    request: operations.ListAuditEvidenceRequest,
    options?: RequestOptions,
  ): Promise<components.PaginatedResponseEvidence> {
    return unwrapAsync(auditsListEvidence(
      this,
      request,
      options,
    ));
  }

  /**
   * Create a custom evidence request for an audit
   *
   * @remarks
   * Create a custom evidence request for an audit.
   *
   * Rate limit: 10 requests / minute.
   */
  async createCustomEvidenceRequest(
    request: operations.CreateCustomEvidenceRequestRequest,
    options?: RequestOptions,
  ): Promise<components.CustomEvidenceRequest> {
    return unwrapAsync(auditsCreateCustomEvidenceRequest(
      this,
      request,
      options,
    ));
  }

  /**
   * Update audit evidence
   *
   * @remarks
   * Update audit evidence.
   *
   * Rate limit: 10 requests / minute.
   */
  async updateEvidence(
    request: operations.UpdateAuditEvidenceRequest,
    options?: RequestOptions,
  ): Promise<components.Evidence> {
    return unwrapAsync(auditsUpdateEvidence(
      this,
      request,
      options,
    ));
  }

  /**
   * Create a comment for audit evidence
   *
   * @remarks
   * Create a comment in Vanta for a piece of evidence.
   *
   * Rate limit: 10 requests / minute.
   */
  async createCommentForEvidence(
    request: operations.CreateCommentForAuditEvidenceRequest,
    options?: RequestOptions,
  ): Promise<components.Comment> {
    return unwrapAsync(auditsCreateCommentForEvidence(
      this,
      request,
      options,
    ));
  }

  /**
   * List audit evidence url
   *
   * @remarks
   * Returns a paginated list of evidence urls for an audit. This endpoint should be called whenever an
   * evidence is created or has a statusUpdatedAt field that is more recent than the most recent polling event.
   *
   * Evidence must be in one of the following states to retrieve URLs: "Ready for audit", "Accepted", "Flagged", or "NA".
   *
   * Rate limit: 600 requests / minute.
   */
  async getEvidenceUrls(
    request: operations.ListAuditEvidenceUrlsRequest,
    options?: RequestOptions,
  ): Promise<components.PaginatedResponseEvidenceUrl> {
    return unwrapAsync(auditsGetEvidenceUrls(
      this,
      request,
      options,
    ));
  }

  /**
   * Get framework codes for an audit
   *
   * @remarks
   * Retrieves all valid framework codes for the specified audit. This endpoint helps users discover which framework codes are available for creating and updating information requests for this audit.
   *
   * Use this endpoint to:
   * - Discover available framework codes before creating information requests
   * - Validate framework codes against the audit's framework
   * - Get context about what framework codes are available for the audit type
   *
   * Rate limit: 10 requests / minute.
   */
  async getFrameworkCodes(
    request: operations.GetFrameworkCodesRequest,
    options?: RequestOptions,
  ): Promise<components.FrameworkCodes> {
    return unwrapAsync(auditsGetFrameworkCodes(
      this,
      request,
      options,
    ));
  }

  /**
   * List information requests for an audit
   *
   * @remarks
   * Retrieves a paginated list of all information requests for an audit, enabling
   * external audit management systems to display and track evidence requests.
   *
   * This endpoint always includes soft-deleted records (where `deletionDate !== null`).
   * Clients should check the `deletionDate` field to identify and handle deleted records
   * appropriately in their systems.
   *
   * This endpoint supports delta synchronization via the `changedSinceDate` parameter,
   * allowing efficient polling for changes without retrieving the entire dataset.
   *
   * Pagination usage:
   * 1. Make initial request with desired `pageSize`
   * 2. Check `results.pageInfo.hasNextPage` to see if more data exists
   * 3. If true, use `results.pageInfo.endCursor` as `pageCursor` in next request
   * 4. Repeat until `hasNextPage` is false
   *
   * Delta sync usage:
   * 1. Store the timestamp of your last sync
   * 2. Pass that timestamp as `changedSinceDate`
   * 3. Only requests created, modified, or deleted since that timestamp are returned
   * 4. Process updates and soft-deletes by checking the `deletionDate` field
   * 5. Update your last sync timestamp to the current time
   *
   * Rate limit: 50 requests / minute.
   */
  async listInformationRequests(
    request: operations.ListInformationRequestsRequest,
    options?: RequestOptions,
  ): Promise<components.PaginatedResponseInformationRequest> {
    return unwrapAsync(auditsListInformationRequests(
      this,
      request,
      options,
    ));
  }

  /**
   * Create a new information request
   *
   * @remarks
   * Creates a new information request for an audit during audit setup or as requirements evolve.
   *
   * After creating all information requests, use POST /audits/{auditId}/share-information-request-list
   * to make them visible to the customer organization. Until shared, requests remain in draft state
   * visible only to auditors.
   *
   * New requests are created in an initial state indicating evidence is needed. The status
   * progresses through the workflow: initial state → awaiting review → approved or flagged.
   *
   * Rate limit: 600 requests / minute.
   */
  async createInformationRequest(
    request: operations.CreateInformationRequestRequest,
    options?: RequestOptions,
  ): Promise<components.InformationRequest> {
    return unwrapAsync(auditsCreateInformationRequest(
      this,
      request,
      options,
    ));
  }

  /**
   * Get an information request by ID
   *
   * @remarks
   * Retrieves a single information request by its ID for an audit, allowing external
   * audit management systems to fetch the latest state of a specific request without
   * paginating through the full list.
   *
   * Soft-deleted records (where `deletionDate !== null`) are included in the response.
   * Clients should check `deletionDate` to determine whether the request has been deleted.
   *
   * Rate limit: 50 requests / minute.
   */
  async getInformationRequest(
    request: operations.GetInformationRequestRequest,
    options?: RequestOptions,
  ): Promise<components.InformationRequest> {
    return unwrapAsync(auditsGetInformationRequest(
      this,
      request,
      options,
    ));
  }

  /**
   * Update an information request for an audit
   *
   * @remarks
   * Updates an existing information request for an audit, allowing modification of request
   * details as audit requirements evolve. Supports partial updates where only specified
   * fields are changed; omitted fields remain unchanged.
   *
   * Common use cases:
   * - Updating due dates as audit timelines shift
   * - Refining descriptions to clarify requirements
   * - Adjusting request type
   *
   * Note: The `modificationDate` is automatically updated to the current timestamp
   * when any field is changed.
   *
   * Rate limit: 50 requests / minute.
   */
  async updateInformationRequest(
    request: operations.UpdateInformationRequestRequest,
    options?: RequestOptions,
  ): Promise<components.InformationRequest> {
    return unwrapAsync(auditsUpdateInformationRequest(
      this,
      request,
      options,
    ));
  }

  /**
   * Delete an information request for an audit
   *
   * @remarks
   * Deletes an information request for an audit. This performs a soft delete, marking
   * the request as deleted (setting `deletionDate`) while preserving it in the system
   * for audit history and compliance tracking.
   *
   * Soft deletion allows:
   * - Maintaining complete audit trail of all requests ever created
   * - Retrieving deleted requests via `changedSinceDate` for synchronization
   *
   * After deletion:
   * - The request will not appear in normal list responses (without `changedSinceDate`)
   * - The request's `deletionDate` field will be populated
   *
   * Rate limit: 10 requests / minute.
   */
  async deleteInformationRequest(
    request: operations.DeleteInformationRequestRequest,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(auditsDeleteInformationRequest(
      this,
      request,
      options,
    ));
  }

  /**
   * Accept evidence for an information request
   *
   * @remarks
   * Accepts evidence for an information request, confirming that all submitted evidence
   * meets audit requirements. This action changes the request's approvalStatus to
   * an approved state and creates an activity log entry.
   *
   * Acceptance workflow:
   * 1. Auditor reviews submitted evidence
   * 2. If evidence is satisfactory, auditor calls this endpoint
   * 3. Request status changes to approved state and is considered complete for this audit cycle
   *
   * Use this endpoint when:
   * - All required evidence has been submitted
   * - Evidence quality meets audit standards
   * - Evidence addresses all specified framework codes
   * - No additional information is needed
   *
   * Rate limit: 50 requests / minute.
   */
  async acceptInformationRequestEvidence(
    request: operations.AcceptInformationRequestEvidenceRequest,
    options?: RequestOptions,
  ): Promise<components.InformationRequest> {
    return unwrapAsync(auditsAcceptInformationRequestEvidence(
      this,
      request,
      options,
    ));
  }

  /**
   * List information request activity
   *
   * @remarks
   * Retrieves a paginated list of activity logs for an information request, providing
   * a complete audit trail of all changes and actions.
   *
   * This endpoint supports delta synchronization via the `changedSinceDate` parameter,
   * allowing efficient polling for changes without retrieving the entire dataset.
   *
   * Pagination usage:
   * 1. Make initial request with desired `pageSize`
   * 2. Check `results.pageInfo.hasNextPage` to see if more data exists
   * 3. If true, use `results.pageInfo.endCursor` as `pageCursor` in next request
   * 4. Repeat until `hasNextPage` is false
   *
   * Delta sync usage:
   * 1. Store the timestamp of your last sync
   * 2. Pass that timestamp as `changedSinceDate`
   * 3. Only activity created since that timestamp is returned
   * 4. Process updates to track all changes to the information request
   * 5. Update your last sync timestamp to the current time
   *
   * Rate limit: 50 requests / minute.
   */
  async listInformationRequestActivity(
    request: operations.ListInformationRequestActivityRequest,
    options?: RequestOptions,
  ): Promise<components.PaginatedResponseInformationRequestActivityLog> {
    return unwrapAsync(auditsListInformationRequestActivity(
      this,
      request,
      options,
    ));
  }

  /**
   * List comments for an information request
   *
   * @remarks
   * Retrieves a paginated list of comments for an information request, enabling
   * auditors to view communication history and collaborate with customers.
   *
   * This endpoint always includes soft-deleted records (where `deletionDate !== null`).
   * Clients should check the `deletionDate` field to identify and handle deleted records
   * appropriately in their systems.
   *
   * This endpoint supports delta synchronization via the `changedSinceDate` parameter,
   * allowing efficient polling for changes without retrieving the entire dataset.
   *
   * Pagination usage:
   * 1. Make initial request with desired `pageSize`
   * 2. Check `results.pageInfo.hasNextPage` to see if more data exists
   * 3. If true, use `results.pageInfo.endCursor` as `pageCursor` in next request
   * 4. Repeat until `hasNextPage` is false
   *
   * Delta sync usage:
   * 1. Store the timestamp of your last sync
   * 2. Pass that timestamp as `changedSinceDate`
   * 3. Only comments created, modified, or deleted since that timestamp are returned
   * 4. Process updates, including soft-deletes (deletionDate !== null)
   * 5. Update your last sync timestamp to the current time
   *
   * Rate limit: 50 requests / minute.
   */
  async listCommentsForInformationRequest(
    request: operations.ListCommentsForInformationRequestRequest,
    options?: RequestOptions,
  ): Promise<components.PaginatedResponseInformationRequestComment> {
    return unwrapAsync(auditsListCommentsForInformationRequest(
      this,
      request,
      options,
    ));
  }

  /**
   * Create a comment for an information request
   *
   * @remarks
   * Creates a new comment for an information request. The comment author must be an auditor
   * in the audit firm making the request. The comment will be associated with the information
   * request and visible to all authorized users.
   *
   * Rate limit: 50 requests / minute.
   */
  async createCommentForInformationRequest(
    request: operations.CreateCommentForInformationRequestRequest,
    options?: RequestOptions,
  ): Promise<components.InformationRequestComment> {
    return unwrapAsync(auditsCreateCommentForInformationRequest(
      this,
      request,
      options,
    ));
  }

  /**
   * Update a comment for an information request
   *
   * @remarks
   * Updates an existing comment for an information request. Only the original author
   * of the comment can update it. The author is identified by their email address,
   * which must match the email of the user who created the comment.
   *
   * Rate limit: 10 requests / minute.
   */
  async updateCommentForInformationRequest(
    request: operations.UpdateCommentForInformationRequestRequest,
    options?: RequestOptions,
  ): Promise<components.InformationRequestComment> {
    return unwrapAsync(auditsUpdateCommentForInformationRequest(
      this,
      request,
      options,
    ));
  }

  /**
   * Delete a comment for an information request
   *
   * @remarks
   * Deletes an existing comment for an information request. Only the original author
   * of the comment can delete it. The author is identified by their email address,
   * which must match the email of the user who created the comment.
   *
   * Rate limit: 10 requests / minute.
   */
  async deleteCommentForInformationRequest(
    request: operations.DeleteCommentForInformationRequestRequest,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(auditsDeleteCommentForInformationRequest(
      this,
      request,
      options,
    ));
  }

  /**
   * List evidence for an information request
   *
   * @remarks
   * Retrieves a paginated list of all evidence attached to an information request,
   * enabling auditors to review evidence submitted by customers.
   *
   * This endpoint always includes soft-deleted records (where `deletionDate !== null`).
   * Clients should check the `deletionDate` field to identify and handle deleted records
   * appropriately in their systems.
   *
   * This endpoint supports delta synchronization via the `changedSinceDate` parameter,
   * allowing efficient polling for changes without retrieving the entire dataset.
   *
   * Pagination usage:
   * 1. Make initial request with desired `pageSize`
   * 2. Check `results.pageInfo.hasNextPage` to see if more data exists
   * 3. If true, use `results.pageInfo.endCursor` as `pageCursor` in next request
   * 4. Repeat until `hasNextPage` is false
   *
   * Delta sync usage:
   * 1. Store the timestamp of your last sync
   * 2. Pass that timestamp as `changedSinceDate`
   * 3. Only evidence created, modified, shared, or deleted since that timestamp is returned
   * 4. Process updates, including soft-deletes (deletionDate !== null)
   * 5. Update your last sync timestamp to the current time
   *
   * Rate limit: 50 requests / minute.
   */
  async listInformationRequestEvidence(
    request: operations.ListInformationRequestEvidenceRequest,
    options?: RequestOptions,
  ): Promise<components.PaginatedResponseInformationRequestEvidence> {
    return unwrapAsync(auditsListInformationRequestEvidence(
      this,
      request,
      options,
    ));
  }

  /**
   * Get test snapshot detail for an evidence row
   *
   * @remarks
   * Retrieves the rich detail for a single VANTA_TEST_SNAPSHOT evidence row
   * attached to an information request. The response includes test-level
   * metadata (description, integrations, SLA), the raw test data captured
   * at snapshot time, and the resources that were excluded from the test
   * (out-of-scope resources).
   *
   * For structured snapshots, the `rawTestData` array contains one row per
   * resource the test ran against; each row carries `resourceId`,
   * `resourceType`, and the raw JSON for that resource.
   *
   * For unstructured snapshots, the `rawTestData` array contains a single
   * row with `resourceId` and `resourceType` set to `null` and `rawJson`
   * containing the entire test-run JSON blob.
   *
   * The `outOfScopeResources` field lists resources excluded at the test
   * level (customer-disabled) and the framework level (segment
   * configuration). Empty exclusion groups are filtered out.
   *
   * The `apiRequests` array contains the HTTP requests captured during API
   * introspection tests. Empty when the test does not perform API
   * introspection.
   *
   * Rate limit: 10 requests / minute.
   */
  async getInformationRequestTestSnapshotEvidenceDetail(
    request: operations.GetInformationRequestTestSnapshotEvidenceDetailRequest,
    options?: RequestOptions,
  ): Promise<components.VantaTestSnapshotEvidenceDetail> {
    return unwrapAsync(auditsGetInformationRequestTestSnapshotEvidenceDetail(
      this,
      request,
      options,
    ));
  }

  /**
   * Flag evidence for an information request
   *
   * @remarks
   * Flags evidence for an information request when it doesn't meet audit requirements,
   * marking issues that need to be addressed before approval. This action changes the
   * request's approvalStatus to a flagged state and creates an activity log entry.
   *
   * Flagging workflow:
   * 1. Auditor reviews submitted evidence
   * 2. If issues are found, auditor calls this endpoint with detailed reason
   * 3. Request status changes to flagged state
   * 4. Customer is notified and can see the reason in activity logs
   * 5. Customer addresses issues and updates evidence
   * 6. When ready, customer changes status back to awaiting review
   * 7. Auditor reviews again and either flags again or accepts
   *
   * The `reason` field should clearly explain what's missing or incorrect so the
   * customer knows exactly what to fix. This reason is visible to the customer
   * and appears in the activity log.
   *
   * Rate limit: 50 requests / minute.
   */
  async flagInformationRequestEvidence(
    request: operations.FlagInformationRequestEvidenceRequest,
    options?: RequestOptions,
  ): Promise<components.InformationRequest> {
    return unwrapAsync(auditsFlagInformationRequestEvidence(
      this,
      request,
      options,
    ));
  }

  /**
   * List snapshotted issues for an audit
   *
   * @remarks
   * Retrieves a list of all issues that have been shared with an audit.
   *
   * The issues returned are immutable, point-in-time snapshots; there may be duplicates of issues that have been snapshotted at different times.
   * The GET /audits/{auditId}/issues/snapshots endpoint can be used to retrieve metadata about the snapshots that issues belong to.
   * Issues represent compliance findings from a variety of sources that need to be tracked and remediated.
   *
   * Supports filtering by:
   * - `search`: full text search across issue title and description
   * - `snapshotId`: filtering to a specific snapshot or snapshots, which represent point-in-time captures of issues. Use the GET /audits/{auditId}/issues/snapshots endpoint to retrieve snapshot IDs and metadata.
   * - `createdAfterDate` / `createdBeforeDate`: filter to issues created within a date range (inclusive)
   * - `detectedAfterDate` / `detectedBeforeDate`: filter to issues detected within a date range (inclusive)
   *
   * Results are sorted by issue creation date in descending order (newest first) by default.
   * Use `orderBy` and `orderDirection` to customize sorting.
   * Sort parameters must remain consistent across paginated requests.
   *
   * Uses cursor-based pagination. To paginate:
   * 1. Make initial request with desired `pageSize`
   * 2. Check `results.pageInfo.hasNextPage`
   * 3. Use `results.pageInfo.endCursor` as `pageCursor` for next request
   *
   * Rate limit: 10 requests / minute.
   */
  async listAuditIssues(
    request: operations.ListAuditIssuesRequest,
    options?: RequestOptions,
  ): Promise<components.PaginatedIssueSnapshotItemsResponse> {
    return unwrapAsync(auditsListAuditIssues(
      this,
      request,
      options,
    ));
  }

  /**
   * List snapshotted issues for an audit
   *
   * @remarks
   * Retrieves a list of snapshots that have been shared with an audit.
   *
   * The snapshots returned contain metadata about point-in-time captures of issues for an audit.
   * This data can be used to filter down the list of issues to specific snapshots when querying the GET /audits/{auditId}/issues/items endpoint.
   *
   * Supports filtering by:
   * - `search`: full text search across snapshot title and description
   *
   * Results are sorted by snapshot creation date in descending order (newest first).
   *
   * Uses cursor-based pagination. To paginate:
   * 1. Make initial request with desired `pageSize`
   * 2. Check `results.pageInfo.hasNextPage`
   * 3. Use `results.pageInfo.endCursor` as `pageCursor` for next request
   *
   * Rate limit: 10 requests / minute.
   */
  async listAuditSnapshots(
    request: operations.ListAuditSnapshotsRequest,
    options?: RequestOptions,
  ): Promise<components.PaginatedIssueSnapshotMetadataResponse> {
    return unwrapAsync(auditsListAuditSnapshots(
      this,
      request,
      options,
    ));
  }

  /**
   * List vendors for an audit
   *
   * @remarks
   * Retrieves vendor population data for an audit.
   *
   * This endpoint provides access to vendor records visible to auditors
   * during an audit engagement.
   *
   * Supports filtering by:
   * - `search`: Searches vendor names (case-insensitive)
   * - `vendorStatusesMatchesAny`: Filters by vendor status (ACTIVE, ARCHIVED, IN_PROCUREMENT)
   * - `inherentRiskMatchesAny`: Filters by inherent risk level
   *
   * Results are sorted by name (ascending) by default.
   * Use `orderBy` and `orderDirection` to customize sorting.
   * Sort parameters must remain consistent across paginated requests.
   *
   * Uses cursor-based pagination. To paginate:
   * 1. Make initial request with desired `pageSize`
   * 2. Check `results.pageInfo.hasNextPage`
   * 3. Use `results.pageInfo.endCursor` as `pageCursor` for next request
   *
   * Rate limit: 10 requests / minute.
   */
  async listVendors(
    request: operations.ListVendorsRequest,
    options?: RequestOptions,
  ): Promise<components.PaginatedResponseAuditVendor> {
    return unwrapAsync(auditsListVendors(
      this,
      request,
      options,
    ));
  }

  /**
   * List monitored computers
   *
   * @remarks
   * Returns a list of computers monitored by an MDM (with an integration built
   * by Vanta) or by Vanta Device Monitor. Currently this list does not include
   * resources from partner or customer-built integrations.
   *
   * End of life — this endpoint works for classic audits only; it does not support
   * controlled audit view. It remains available for existing classic audits but will be removed once
   * classic audits are fully phased out, so do not build new integrations on it.
   *
   * Rate limit: 10 requests / minute.
   *
   * @deprecated method: This will be removed in a future release, please migrate away from it as soon as possible.
   */
  async listMonitoredComputersInAuditScope(
    request: operations.ListMonitoredComputersInAuditScopeRequest,
    options?: RequestOptions,
  ): Promise<components.PaginatedResponseMonitoredComputer> {
    return unwrapAsync(auditsListMonitoredComputersInAuditScope(
      this,
      request,
      options,
    ));
  }

  /**
   * List of people who are in scope for this audit
   *
   * @remarks
   * Returns a list of people who are in scope for this audit.
   *
   * End of life — this endpoint works for classic audits only; it does not support
   * controlled audit view. It remains available for existing classic audits but will be removed once
   * classic audits are fully phased out, so do not build new integrations on it.
   *
   * Rate limit: 10 requests / minute.
   *
   * @deprecated method: This will be removed in a future release, please migrate away from it as soon as possible.
   */
  async listPeopleInAuditScope(
    request: operations.ListPeopleInAuditScopeRequest,
    options?: RequestOptions,
  ): Promise<components.PaginatedResponsePerson> {
    return unwrapAsync(auditsListPeopleInAuditScope(
      this,
      request,
      options,
    ));
  }

  /**
   * List account access services for an audit
   *
   * @remarks
   * Retrieves connected account access services for an audit.
   *
   * Returns the list of identity providers and access integrations (such as
   * Okta, Azure AD, Google Workspace, AWS IAM) that are connected to the
   * organization and provide account access data for personnel.
   *
   * These integrations are used to verify user access and identity management
   * during an audit engagement.
   *
   * Uses cursor-based pagination. To paginate:
   * 1. Make initial request with desired `pageSize`
   * 2. Check `results.pageInfo.hasNextPage`
   * 3. Use `results.pageInfo.endCursor` as `pageCursor` for next request
   *
   * Results are returned in connection order. Sort order is not guaranteed
   * and cannot be customized via query parameters.
   *
   * Rate limit: 10 requests / minute.
   */
  async listAccountAccessServices(
    request: operations.ListAccountAccessServicesRequest,
    options?: RequestOptions,
  ): Promise<components.PaginatedResponseAccountAccessService> {
    return unwrapAsync(auditsListAccountAccessServices(
      this,
      request,
      options,
    ));
  }

  /**
   * List account access records for an audit
   *
   * @remarks
   * Retrieves account access population data for an audit.
   *
   * This endpoint provides access to account access records visible to auditors
   * during an audit engagement. Account access data comes from various sources:
   *
   * - **IDP Services** (Identity Providers): Okta, Azure AD, Google Workspace, OneLogin, PingOne
   *
   *   - Returns user accounts from identity providers
   *   - Supports filtering by search and status
   *
   * - **Role Grants Services**: GCP, Azure (when role grants are enabled)
   *
   *   - Returns accounts with role-based access grants
   *   - Supports filtering by search and status
   *
   * - **First-Party Account Services**: AWS, Oracle Cloud, Azure (when not using role grants), etc.
   *
   *   - Returns cloud provider account access records
   *   - Supports filtering by search and status
   *
   * - **Received Account Services**: External applications (Jira, GitHub, Slack, etc.)
   *
   *   - Returns user accounts from third-party integrations
   *   - Supports filtering by search and status
   *
   * Supports filtering by:
   * - `search`: Searches account names/emails (case-insensitive)
   * - `status`: Filters by account status
   *
   * Uses cursor-based pagination. To paginate:
   * 1. Make initial request with desired `pageSize`
   * 2. Check `results.pageInfo.hasNextPage`
   * 3. Use `results.pageInfo.endCursor` as `pageCursor` for next request
   *
   * The default sort order depends on the service type:
   * - Identity provider services (e.g. Okta, Azure AD): sorted by email, ascending
   * - Cloud provider services (e.g. AWS, GCP): sorted by account name, ascending
   * - Role grant services: sorted by account name, ascending
   * - Third-party application services (e.g. GitHub, Jira): sorted by account name, ascending
   *
   * Sort order cannot be customized via query parameters.
   *
   * Rate limit: 10 requests / minute.
   */
  async listPersonnelAccountAccess(
    request: operations.ListPersonnelAccountAccessRequest,
    options?: RequestOptions,
  ): Promise<components.PaginatedResponseAccountAccess> {
    return unwrapAsync(auditsListPersonnelAccountAccess(
      this,
      request,
      options,
    ));
  }

  /**
   * List groups for an audit
   *
   * @remarks
   * Retrieves groups population data for an audit.
   *
   * This endpoint provides access to the group records visible to auditors
   * during an audit engagement. Groups represent organizational units that
   * contain people, either imported from an identity provider (IDP) or
   * created manually in Vanta.
   *
   * Only Controlled Audit View (CAV) audits are supported. Full Audit
   * View audits are rejected with 403.
   *
   * Supports filtering by:
   * - `search`: Searches group names (case-insensitive)
   * - `sourcesMatchesAny`: Filters by IDP source service names
   *
   * Results are sorted by name (ascending) by default.
   * Use `orderBy` and `orderDirection` to customize sorting.
   * Sort parameters must remain consistent across paginated requests.
   *
   * Uses cursor-based pagination. To paginate:
   * 1. Make initial request with desired `pageSize`
   * 2. Check `results.pageInfo.hasNextPage`
   * 3. Use `results.pageInfo.endCursor` as `pageCursor` for next request
   *
   * Rate limit: 10 requests / minute.
   */
  async listPersonnelGroups(
    request: operations.ListPersonnelGroupsRequest,
    options?: RequestOptions,
  ): Promise<components.PaginatedResponsePersonnelGroup> {
    return unwrapAsync(auditsListPersonnelGroups(
      this,
      request,
      options,
    ));
  }

  /**
   * List people for an audit
   *
   * @remarks
   * Retrieves people population data for an audit.
   *
   * This endpoint provides access to the people records visible to auditors
   * during an audit engagement. Only Controlled Audit View (CAV) audits
   * are supported. Full Audit View audits are rejected with 403.
   *
   * Supports filtering by:
   * - `search`: Searches names and email addresses
   * - `status`: Filters by employment status
   * - `groupsMatchesAny`: Filter people by group/role IDs
   *
   * Results are sorted by name (ascending) by default.
   * Use `orderBy` and `orderDirection` to customize sorting.
   * Sort parameters must remain consistent across paginated requests.
   *
   * Uses cursor-based pagination. To paginate:
   * 1. Make initial request with desired `pageSize`
   * 2. Check `results.pageInfo.hasNextPage`
   * 3. Use `results.pageInfo.endCursor` as `pageCursor` for next request
   *
   * Rate limit: 10 requests / minute.
   */
  async listPersonnelPeople(
    request: operations.ListPersonnelPeopleRequest,
    options?: RequestOptions,
  ): Promise<components.PaginatedResponsePersonnelPerson> {
    return unwrapAsync(auditsListPersonnelPeople(
      this,
      request,
      options,
    ));
  }

  /**
   * List risk snapshots for an audit
   *
   * @remarks
   * Returns a paginated list of risk assessment snapshots available for an audit.
   *
   * Risk snapshots capture the state of an organization's risk register at a
   * point in time. Each snapshot has an `id` that can be used with the
   * `/audits/{auditId}/risks` endpoint to retrieve the individual risk
   * scenarios within that snapshot.
   *
   * Results are sorted by creation date (newest first). This sort order is
   * fixed and cannot be customized via query parameters. Only snapshots
   * that are shared with auditors are included.
   *
   * Uses cursor-based pagination. To paginate:
   * 1. Make initial request with desired `pageSize`
   * 2. Check `results.pageInfo.hasNextPage`
   * 3. Use `results.pageInfo.endCursor` as `pageCursor` for next request
   *
   * Rate limit: 10 requests / minute.
   */
  async listRiskSnapshots(
    request: operations.ListRiskSnapshotsRequest,
    options?: RequestOptions,
  ): Promise<components.PaginatedResponseRiskSnapshot> {
    return unwrapAsync(auditsListRiskSnapshots(
      this,
      request,
      options,
    ));
  }

  /**
   * List risks for an audit
   *
   * @remarks
   * Retrieves risk population data for an audit.
   *
   * This endpoint provides access to the risk records visible to auditors
   * during an audit engagement. Risk data is scoped to a specific risk
   * assessment snapshot identified by the `snapshotId` parameter.
   *
   * Only Controlled Audit View (CAV) audits are supported. Full Audit
   * View audits are rejected with 403.
   *
   * Supports filtering by:
   * - `search`: Searches risk scenario descriptions (case-insensitive)
   *
   * Results are sorted by identified date (newest first) by default.
   * Use `orderBy` and `orderDirection` to customize sorting.
   * Sort parameters must remain consistent across paginated requests.
   *
   * Uses cursor-based pagination. To paginate:
   * 1. Make initial request with desired `pageSize`
   * 2. Check `results.pageInfo.hasNextPage`
   * 3. Use `results.pageInfo.endCursor` as `pageCursor` for next request
   *
   * Rate limit: 10 requests / minute.
   */
  async listAuditRisks(
    request: operations.ListAuditRisksRequest,
    options?: RequestOptions,
  ): Promise<components.PaginatedResponseAuditRisk> {
    return unwrapAsync(auditsListAuditRisks(
      this,
      request,
      options,
    ));
  }

  /**
   * Share information request list with customer
   *
   * @remarks
   * Shares the current information request list for an audit with the customer organization,
   * making it visible in their portal. This action allows the customer to see all information
   * requests that have been created for their audit. Only IRL audits are supported.
   *
   * Rate limit: 10 requests / minute.
   */
  async shareInformationRequestList(
    request: operations.ShareInformationRequestListRequest,
    options?: RequestOptions,
  ): Promise<components.Audit> {
    return unwrapAsync(auditsShareInformationRequestList(
      this,
      request,
      options,
    ));
  }

  /**
   * List of vendors who are in scope for this audit
   *
   * @remarks
   * Returns a list of vendors who are in scope for this audit.
   *
   * End of life — this endpoint works for classic audits only; it does not support
   * controlled audit view. It remains available for existing classic audits but will be removed once
   * classic audits are fully phased out, so do not build new integrations on it.
   *
   * Rate limit: 10 requests / minute.
   *
   * @deprecated method: This will be removed in a future release, please migrate away from it as soon as possible.
   */
  async listVendorsInAuditScope(
    request: operations.ListVendorsInAuditScopeRequest,
    options?: RequestOptions,
  ): Promise<components.PaginatedResponseVendor> {
    return unwrapAsync(auditsListVendorsInAuditScope(
      this,
      request,
      options,
    ));
  }

  /**
   * List vulnerabilities within the scope of a given audit
   *
   * @remarks
   * List all vulnerabilities based on selected filters.
   *
   * End of life — this endpoint works for classic audits only; it does not support
   * controlled audit view. It remains available for existing classic audits but will be removed once
   * classic audits are fully phased out, so do not build new integrations on it.
   *
   * Rate limit: 10 requests / minute.
   *
   * @deprecated method: This will be removed in a future release, please migrate away from it as soon as possible.
   */
  async listVulnerabilities(
    request: operations.ListVulnerabilitiesRequest,
    options?: RequestOptions,
  ): Promise<components.PaginatedResponseAuditorApiVulnerability> {
    return unwrapAsync(auditsListVulnerabilities(
      this,
      request,
      options,
    ));
  }

  /**
   * List vulnerability remediations that are in scope for this audit
   *
   * @remarks
   * List all vulnerability remediations based on selected filters that are in scope for this audit.
   *
   * End of life — this endpoint works for classic audits only; it does not support
   * controlled audit view. It remains available for existing classic audits but will be removed once
   * classic audits are fully phased out, so do not build new integrations on it.
   *
   * Rate limit: 10 requests / minute.
   *
   * @deprecated method: This will be removed in a future release, please migrate away from it as soon as possible.
   */
  async listVulnerabilityRemediationsInAuditScope(
    request: operations.ListVulnerabilityRemediationsInAuditScopeRequest,
    options?: RequestOptions,
  ): Promise<components.PaginatedResponseVulnerabilityRemediation> {
    return unwrapAsync(auditsListVulnerabilityRemediationsInAuditScope(
      this,
      request,
      options,
    ));
  }

  /**
   * List assets associated with vulnerabilities
   *
   * @remarks
   * List assets that Vanta monitors that are associated with vulnerabilities.
   *
   * End of life — this endpoint works for classic audits only; it does not support
   * controlled audit view. It remains available for existing classic audits but will be removed once
   * classic audits are fully phased out, so do not build new integrations on it.
   *
   * Rate limit: 10 requests / minute.
   *
   * @deprecated method: This will be removed in a future release, please migrate away from it as soon as possible.
   */
  async getVulnerableAssets(
    request: operations.GetVulnerableAssetsRequest,
    options?: RequestOptions,
  ): Promise<components.PaginatedResponseVulnerableAsset> {
    return unwrapAsync(auditsGetVulnerableAssets(
      this,
      request,
      options,
    ));
  }
}
