/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { auditsAcceptInformationRequestEvidence } from "../funcs/auditsAcceptInformationRequestEvidence.js";
import { auditsCreateCommentForEvidence } from "../funcs/auditsCreateCommentForEvidence.js";
import { auditsCreateCommentForInformationRequest } from "../funcs/auditsCreateCommentForInformationRequest.js";
import { auditsCreateCustomControl } from "../funcs/auditsCreateCustomControl.js";
import { auditsCreateCustomEvidenceRequest } from "../funcs/auditsCreateCustomEvidenceRequest.js";
import { auditsCreateInformationRequest } from "../funcs/auditsCreateInformationRequest.js";
import { auditsDeleteCommentForInformationRequest } from "../funcs/auditsDeleteCommentForInformationRequest.js";
import { auditsDeleteInformationRequest } from "../funcs/auditsDeleteInformationRequest.js";
import { auditsFlagInformationRequestEvidence } from "../funcs/auditsFlagInformationRequestEvidence.js";
import { auditsGetAudit } from "../funcs/auditsGetAudit.js";
import { auditsGetEvidenceUrls } from "../funcs/auditsGetEvidenceUrls.js";
import { auditsGetFrameworkCodes } from "../funcs/auditsGetFrameworkCodes.js";
import { auditsGetInformationRequest } from "../funcs/auditsGetInformationRequest.js";
import { auditsGetInformationRequestTestSnapshotEvidenceDetail } from "../funcs/auditsGetInformationRequestTestSnapshotEvidenceDetail.js";
import { auditsList } from "../funcs/auditsList.js";
import { auditsListAuditIssues } from "../funcs/auditsListAuditIssues.js";
import { auditsListAuditSnapshots } from "../funcs/auditsListAuditSnapshots.js";
import { auditsListComments } from "../funcs/auditsListComments.js";
import { auditsListCommentsForInformationRequest } from "../funcs/auditsListCommentsForInformationRequest.js";
import { auditsListControls } from "../funcs/auditsListControls.js";
import { auditsListEvidence } from "../funcs/auditsListEvidence.js";
import { auditsListInformationRequestActivity } from "../funcs/auditsListInformationRequestActivity.js";
import { auditsListInformationRequestEvidence } from "../funcs/auditsListInformationRequestEvidence.js";
import { auditsListInformationRequests } from "../funcs/auditsListInformationRequests.js";
import { auditsListInformationRequestsForControl } from "../funcs/auditsListInformationRequestsForControl.js";
import { auditsShareInformationRequestList } from "../funcs/auditsShareInformationRequestList.js";
import { auditsUpdateCommentForInformationRequest } from "../funcs/auditsUpdateCommentForInformationRequest.js";
import { auditsUpdateEvidence } from "../funcs/auditsUpdateEvidence.js";
import { auditsUpdateInformationRequest } from "../funcs/auditsUpdateInformationRequest.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Audits extends ClientSDK {
  /**
   * List audits
   *
   * @remarks
   * Returns a paginated list of audits scoped to the audit firm.
   *
   * To identify IRL (Information Request List) audits, check for the presence of the
   * `auditorRequestListMetadata` field. This field is only present for IRL-based audits
   * and will be `undefined` for standard audits.
   */
  async list(
    request: operations.ListAuditsRequest,
    options?: RequestOptions,
  ): Promise<components.PaginatedResponseAudit> {
    return unwrapAsync(auditsList(
      this,
      request,
      options,
    ));
  }

  /**
   * Get audit by ID
   *
   * @remarks
   * Returns a single audit by ID, scoped to the audit firm.
   *
   * To identify IRL (Information Request List) audits, check for the presence of the
   * `auditorRequestListMetadata` field. This field is only present for IRL-based audits
   * and will be `undefined` for standard audits.
   */
  async getAudit(
    request: operations.GetAuditRequest,
    options?: RequestOptions,
  ): Promise<components.Audit> {
    return unwrapAsync(auditsGetAudit(
      this,
      request,
      options,
    ));
  }

  /**
   * List audit comments
   *
   * @remarks
   * Returns a paginated list of comments for an audit.
   */
  async listComments(
    request: operations.ListAuditCommentsRequest,
    options?: RequestOptions,
  ): Promise<components.PaginatedResponseComment> {
    return unwrapAsync(auditsListComments(
      this,
      request,
      options,
    ));
  }

  /**
   * List audit controls
   *
   * @remarks
   * Returns a paginated list of controls for an audit.
   */
  async listControls(
    request: operations.ListAuditControlsRequest,
    options?: RequestOptions,
  ): Promise<components.PaginatedResponseAuditorControl> {
    return unwrapAsync(auditsListControls(
      this,
      request,
      options,
    ));
  }

  /**
   * Create a custom control for an audit
   *
   * @remarks
   * Create a custom control for an audit.
   */
  async createCustomControl(
    request: operations.CreateCustomControlRequest,
    options?: RequestOptions,
  ): Promise<components.Control> {
    return unwrapAsync(auditsCreateCustomControl(
      this,
      request,
      options,
    ));
  }

  /**
   * List information requests linked to a control within an audit
   *
   * @remarks
   * Returns a paginated list of active information requests linked to a specific
   * control within an IRL audit. An information request is linked to a control
   * either via its framework codes (`criteriaIds`) or via a direct association
   * (`additionalControlIds`).
   *
   * Soft-deleted information requests are not included in the response. To
   * synchronize deletions, use `GET /audits/{auditId}/information-requests`,
   * which supports `changedSinceDate` and includes soft-deleted records.
   *
   * Returns 404 when the control is not part of the audit. Returns an empty page
   * when the control is part of the audit but has no active IRLs linked to it.
   *
   * Pagination usage:
   * 1. Make initial request with desired `pageSize`
   * 2. Check `results.pageInfo.hasNextPage` to see if more data exists
   * 3. If true, use `results.pageInfo.endCursor` as `pageCursor` in next request
   * 4. Repeat until `hasNextPage` is false
   */
  async listInformationRequestsForControl(
    request: operations.ListInformationRequestsForControlRequest,
    options?: RequestOptions,
  ): Promise<components.PaginatedResponseInformationRequest> {
    return unwrapAsync(auditsListInformationRequestsForControl(
      this,
      request,
      options,
    ));
  }

  /**
   * List audit evidence
   *
   * @remarks
   * Returns a paginated list of evidence for an audit.
   */
  async listEvidence(
    request: operations.ListAuditEvidenceRequest,
    options?: RequestOptions,
  ): Promise<components.PaginatedResponseEvidence> {
    return unwrapAsync(auditsListEvidence(
      this,
      request,
      options,
    ));
  }

  /**
   * Create a custom evidence request for an audit
   *
   * @remarks
   * Create a custom evidence request for an audit.
   */
  async createCustomEvidenceRequest(
    request: operations.CreateCustomEvidenceRequestRequest,
    options?: RequestOptions,
  ): Promise<components.CustomEvidenceRequest> {
    return unwrapAsync(auditsCreateCustomEvidenceRequest(
      this,
      request,
      options,
    ));
  }

  /**
   * Update audit evidence
   *
   * @remarks
   * Update audit evidence.
   */
  async updateEvidence(
    request: operations.UpdateAuditEvidenceRequest,
    options?: RequestOptions,
  ): Promise<components.Evidence> {
    return unwrapAsync(auditsUpdateEvidence(
      this,
      request,
      options,
    ));
  }

  /**
   * Create a comment for audit evidence
   *
   * @remarks
   * Create a comment in Vanta for a piece of evidence.
   */
  async createCommentForEvidence(
    request: operations.CreateCommentForAuditEvidenceRequest,
    options?: RequestOptions,
  ): Promise<components.Comment> {
    return unwrapAsync(auditsCreateCommentForEvidence(
      this,
      request,
      options,
    ));
  }

  /**
   * List audit evidence url
   *
   * @remarks
   * Returns a paginated list of evidence urls for an audit. This endpoint should be called whenever an
   * evidence is created or has a statusUpdatedAt field that is more recent than the most recent polling event.
   *
   * Evidence must be in one of the following states to retrieve URLs: "Ready for audit", "Accepted", "Flagged", or "NA".
   */
  async getEvidenceUrls(
    request: operations.ListAuditEvidenceUrlsRequest,
    options?: RequestOptions,
  ): Promise<components.PaginatedResponseEvidenceUrl> {
    return unwrapAsync(auditsGetEvidenceUrls(
      this,
      request,
      options,
    ));
  }

  /**
   * Get framework codes for an audit
   *
   * @remarks
   * Retrieves all valid framework codes for the specified audit. This endpoint helps users discover which framework codes are available for creating and updating information requests for this audit.
   *
   * Use this endpoint to:
   * - Discover available framework codes before creating information requests
   * - Validate framework codes against the audit's framework
   * - Get context about what framework codes are available for the audit type
   */
  async getFrameworkCodes(
    request: operations.GetFrameworkCodesRequest,
    options?: RequestOptions,
  ): Promise<components.FrameworkCodes> {
    return unwrapAsync(auditsGetFrameworkCodes(
      this,
      request,
      options,
    ));
  }

  /**
   * List information requests for an audit
   *
   * @remarks
   * Retrieves a paginated list of all information requests for an audit, enabling
   * external audit management systems to display and track evidence requests.
   *
   * This endpoint always includes soft-deleted records (where `deletionDate !== null`).
   * Clients should check the `deletionDate` field to identify and handle deleted records
   * appropriately in their systems.
   *
   * This endpoint supports delta synchronization via the `changedSinceDate` parameter,
   * allowing efficient polling for changes without retrieving the entire dataset.
   *
   * Pagination usage:
   * 1. Make initial request with desired `pageSize`
   * 2. Check `results.pageInfo.hasNextPage` to see if more data exists
   * 3. If true, use `results.pageInfo.endCursor` as `pageCursor` in next request
   * 4. Repeat until `hasNextPage` is false
   *
   * Delta sync usage:
   * 1. Store the timestamp of your last sync
   * 2. Pass that timestamp as `changedSinceDate`
   * 3. Only requests created, modified, or deleted since that timestamp are returned
   * 4. Process updates and soft-deletes by checking the `deletionDate` field
   * 5. Update your last sync timestamp to the current time
   */
  async listInformationRequests(
    request: operations.ListInformationRequestsRequest,
    options?: RequestOptions,
  ): Promise<components.PaginatedResponseInformationRequest> {
    return unwrapAsync(auditsListInformationRequests(
      this,
      request,
      options,
    ));
  }

  /**
   * Create a new information request
   *
   * @remarks
   * Creates a new information request for an audit during audit setup or as requirements evolve.
   *
   * After creating all information requests, use POST /audits/{auditId}/share-information-request-list
   * to make them visible to the customer organization. Until shared, requests remain in draft state
   * visible only to auditors.
   *
   * New requests are created in an initial state indicating evidence is needed. The status
   * progresses through the workflow: initial state → awaiting review → approved or flagged.
   */
  async createInformationRequest(
    request: operations.CreateInformationRequestRequest,
    options?: RequestOptions,
  ): Promise<components.InformationRequest> {
    return unwrapAsync(auditsCreateInformationRequest(
      this,
      request,
      options,
    ));
  }

  /**
   * Get an information request by ID
   *
   * @remarks
   * Retrieves a single information request by its ID for an audit, allowing external
   * audit management systems to fetch the latest state of a specific request without
   * paginating through the full list.
   *
   * Soft-deleted records (where `deletionDate !== null`) are included in the response.
   * Clients should check `deletionDate` to determine whether the request has been deleted.
   */
  async getInformationRequest(
    request: operations.GetInformationRequestRequest,
    options?: RequestOptions,
  ): Promise<components.InformationRequest> {
    return unwrapAsync(auditsGetInformationRequest(
      this,
      request,
      options,
    ));
  }

  /**
   * Update an information request for an audit
   *
   * @remarks
   * Updates an existing information request for an audit, allowing modification of request
   * details as audit requirements evolve. Supports partial updates where only specified
   * fields are changed; omitted fields remain unchanged.
   *
   * Common use cases:
   * - Updating due dates as audit timelines shift
   * - Refining descriptions to clarify requirements
   * - Adjusting request type
   *
   * Note: The `modificationDate` is automatically updated to the current timestamp
   * when any field is changed.
   */
  async updateInformationRequest(
    request: operations.UpdateInformationRequestRequest,
    options?: RequestOptions,
  ): Promise<components.InformationRequest> {
    return unwrapAsync(auditsUpdateInformationRequest(
      this,
      request,
      options,
    ));
  }

  /**
   * Delete an information request for an audit
   *
   * @remarks
   * Deletes an information request for an audit. This performs a soft delete, marking
   * the request as deleted (setting `deletionDate`) while preserving it in the system
   * for audit history and compliance tracking.
   *
   * Soft deletion allows:
   * - Maintaining complete audit trail of all requests ever created
   * - Retrieving deleted requests via `changedSinceDate` for synchronization
   *
   * After deletion:
   * - The request will not appear in normal list responses (without `changedSinceDate`)
   * - The request's `deletionDate` field will be populated
   */
  async deleteInformationRequest(
    request: operations.DeleteInformationRequestRequest,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(auditsDeleteInformationRequest(
      this,
      request,
      options,
    ));
  }

  /**
   * Accept evidence for an information request
   *
   * @remarks
   * Accepts evidence for an information request, confirming that all submitted evidence
   * meets audit requirements. This action changes the request's approvalStatus to
   * an approved state and creates an activity log entry.
   *
   * Acceptance workflow:
   * 1. Auditor reviews submitted evidence
   * 2. If evidence is satisfactory, auditor calls this endpoint
   * 3. Request status changes to approved state and is considered complete for this audit cycle
   *
   * Use this endpoint when:
   * - All required evidence has been submitted
   * - Evidence quality meets audit standards
   * - Evidence addresses all specified framework codes
   * - No additional information is needed
   */
  async acceptInformationRequestEvidence(
    request: operations.AcceptInformationRequestEvidenceRequest,
    options?: RequestOptions,
  ): Promise<components.InformationRequest> {
    return unwrapAsync(auditsAcceptInformationRequestEvidence(
      this,
      request,
      options,
    ));
  }

  /**
   * List information request activity
   *
   * @remarks
   * Retrieves a paginated list of activity logs for an information request, providing
   * a complete audit trail of all changes and actions.
   *
   * This endpoint supports delta synchronization via the `changedSinceDate` parameter,
   * allowing efficient polling for changes without retrieving the entire dataset.
   *
   * Pagination usage:
   * 1. Make initial request with desired `pageSize`
   * 2. Check `results.pageInfo.hasNextPage` to see if more data exists
   * 3. If true, use `results.pageInfo.endCursor` as `pageCursor` in next request
   * 4. Repeat until `hasNextPage` is false
   *
   * Delta sync usage:
   * 1. Store the timestamp of your last sync
   * 2. Pass that timestamp as `changedSinceDate`
   * 3. Only activity created since that timestamp is returned
   * 4. Process updates to track all changes to the information request
   * 5. Update your last sync timestamp to the current time
   */
  async listInformationRequestActivity(
    request: operations.ListInformationRequestActivityRequest,
    options?: RequestOptions,
  ): Promise<components.PaginatedResponseInformationRequestActivityLog> {
    return unwrapAsync(auditsListInformationRequestActivity(
      this,
      request,
      options,
    ));
  }

  /**
   * List comments for an information request
   *
   * @remarks
   * Retrieves a paginated list of comments for an information request, enabling
   * auditors to view communication history and collaborate with customers.
   *
   * This endpoint always includes soft-deleted records (where `deletionDate !== null`).
   * Clients should check the `deletionDate` field to identify and handle deleted records
   * appropriately in their systems.
   *
   * This endpoint supports delta synchronization via the `changedSinceDate` parameter,
   * allowing efficient polling for changes without retrieving the entire dataset.
   *
   * Pagination usage:
   * 1. Make initial request with desired `pageSize`
   * 2. Check `results.pageInfo.hasNextPage` to see if more data exists
   * 3. If true, use `results.pageInfo.endCursor` as `pageCursor` in next request
   * 4. Repeat until `hasNextPage` is false
   *
   * Delta sync usage:
   * 1. Store the timestamp of your last sync
   * 2. Pass that timestamp as `changedSinceDate`
   * 3. Only comments created, modified, or deleted since that timestamp are returned
   * 4. Process updates, including soft-deletes (deletionDate !== null)
   * 5. Update your last sync timestamp to the current time
   */
  async listCommentsForInformationRequest(
    request: operations.ListCommentsForInformationRequestRequest,
    options?: RequestOptions,
  ): Promise<components.PaginatedResponseInformationRequestComment> {
    return unwrapAsync(auditsListCommentsForInformationRequest(
      this,
      request,
      options,
    ));
  }

  /**
   * Create a comment for an information request
   *
   * @remarks
   * Creates a new comment for an information request. The comment author must be an auditor
   * in the audit firm making the request. The comment will be associated with the information
   * request and visible to all authorized users.
   */
  async createCommentForInformationRequest(
    request: operations.CreateCommentForInformationRequestRequest,
    options?: RequestOptions,
  ): Promise<components.InformationRequestComment> {
    return unwrapAsync(auditsCreateCommentForInformationRequest(
      this,
      request,
      options,
    ));
  }

  /**
   * Update a comment for an information request
   *
   * @remarks
   * Updates an existing comment for an information request. Only the original author
   * of the comment can update it. The author is identified by their email address,
   * which must match the email of the user who created the comment.
   */
  async updateCommentForInformationRequest(
    request: operations.UpdateCommentForInformationRequestRequest,
    options?: RequestOptions,
  ): Promise<components.InformationRequestComment> {
    return unwrapAsync(auditsUpdateCommentForInformationRequest(
      this,
      request,
      options,
    ));
  }

  /**
   * Delete a comment for an information request
   *
   * @remarks
   * Deletes an existing comment for an information request. Only the original author
   * of the comment can delete it. The author is identified by their email address,
   * which must match the email of the user who created the comment.
   */
  async deleteCommentForInformationRequest(
    request: operations.DeleteCommentForInformationRequestRequest,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(auditsDeleteCommentForInformationRequest(
      this,
      request,
      options,
    ));
  }

  /**
   * List evidence for an information request
   *
   * @remarks
   * Retrieves a paginated list of all evidence attached to an information request,
   * enabling auditors to review evidence submitted by customers.
   *
   * This endpoint always includes soft-deleted records (where `deletionDate !== null`).
   * Clients should check the `deletionDate` field to identify and handle deleted records
   * appropriately in their systems.
   *
   * This endpoint supports delta synchronization via the `changedSinceDate` parameter,
   * allowing efficient polling for changes without retrieving the entire dataset.
   *
   * Pagination usage:
   * 1. Make initial request with desired `pageSize`
   * 2. Check `results.pageInfo.hasNextPage` to see if more data exists
   * 3. If true, use `results.pageInfo.endCursor` as `pageCursor` in next request
   * 4. Repeat until `hasNextPage` is false
   *
   * Delta sync usage:
   * 1. Store the timestamp of your last sync
   * 2. Pass that timestamp as `changedSinceDate`
   * 3. Only evidence created, modified, shared, or deleted since that timestamp is returned
   * 4. Process updates, including soft-deletes (deletionDate !== null)
   * 5. Update your last sync timestamp to the current time
   */
  async listInformationRequestEvidence(
    request: operations.ListInformationRequestEvidenceRequest,
    options?: RequestOptions,
  ): Promise<components.PaginatedResponseInformationRequestEvidence> {
    return unwrapAsync(auditsListInformationRequestEvidence(
      this,
      request,
      options,
    ));
  }

  /**
   * Get test snapshot detail for an evidence row
   *
   * @remarks
   * Retrieves the rich detail for a single VANTA_TEST_SNAPSHOT evidence row
   * attached to an information request. The response includes test-level
   * metadata (description, integrations, SLA) and the raw test data captured
   * at snapshot time, presented as a uniform array of rows regardless of
   * whether the snapshot is structured or unstructured.
   *
   * For structured snapshots, the array contains one row per resource the
   * test ran against; each row carries `resourceId`, `resourceType`, and the
   * raw JSON for that resource.
   *
   * For unstructured snapshots, the array contains a single row with
   * `resourceId` and `resourceType` set to `null` and `rawJson` containing
   * the entire test-run JSON blob.
   */
  async getInformationRequestTestSnapshotEvidenceDetail(
    request: operations.GetInformationRequestTestSnapshotEvidenceDetailRequest,
    options?: RequestOptions,
  ): Promise<components.VantaTestSnapshotEvidenceDetail> {
    return unwrapAsync(auditsGetInformationRequestTestSnapshotEvidenceDetail(
      this,
      request,
      options,
    ));
  }

  /**
   * Flag evidence for an information request
   *
   * @remarks
   * Flags evidence for an information request when it doesn't meet audit requirements,
   * marking issues that need to be addressed before approval. This action changes the
   * request's approvalStatus to a flagged state and creates an activity log entry.
   *
   * Flagging workflow:
   * 1. Auditor reviews submitted evidence
   * 2. If issues are found, auditor calls this endpoint with detailed reason
   * 3. Request status changes to flagged state
   * 4. Customer is notified and can see the reason in activity logs
   * 5. Customer addresses issues and updates evidence
   * 6. When ready, customer changes status back to awaiting review
   * 7. Auditor reviews again and either flags again or accepts
   *
   * The `reason` field should clearly explain what's missing or incorrect so the
   * customer knows exactly what to fix. This reason is visible to the customer
   * and appears in the activity log.
   */
  async flagInformationRequestEvidence(
    request: operations.FlagInformationRequestEvidenceRequest,
    options?: RequestOptions,
  ): Promise<components.InformationRequest> {
    return unwrapAsync(auditsFlagInformationRequestEvidence(
      this,
      request,
      options,
    ));
  }

  /**
   * List snapshotted issues for an audit
   *
   * @remarks
   * Retrieves a list of all issues that have been shared with an audit.
   *
   * The issues returned are immutable, point-in-time snapshots; there may be duplicates of issues that have been snapshotted at different times.
   * The GET /audits/{auditId}/issues/snapshots endpoint can be used to retrieve metadata about the snapshots that issues belong to.
   * Issues represent compliance findings from a variety of sources that need to be tracked and remediated.
   *
   * Supports filtering by:
   * - `search`: full text search across issue title and description
   * - `snapshotId`: filtering to a specific snapshot or snapshots, which represent point-in-time captures of issues. Use the GET /audits/{auditId}/issues/snapshots endpoint to retrieve snapshot IDs and metadata.
   *
   * Results are sorted by issue creation date in descending order (newest first).
   *
   * Uses cursor-based pagination. To paginate:
   * 1. Make initial request with desired `pageSize`
   * 2. Check `results.pageInfo.hasNextPage`
   * 3. Use `results.pageInfo.endCursor` as `pageCursor` for next request
   */
  async listAuditIssues(
    request: operations.ListAuditIssuesRequest,
    options?: RequestOptions,
  ): Promise<components.PaginatedIssueSnapshotItemsResponse> {
    return unwrapAsync(auditsListAuditIssues(
      this,
      request,
      options,
    ));
  }

  /**
   * List snapshotted issues for an audit
   *
   * @remarks
   * Retrieves a list of snapshots that have been shared with an audit.
   *
   * The snapshots returned contain metadata about point-in-time captures of issues for an audit.
   * This data can be used to filter down the list of issues to specific snapshots when querying the GET /audits/{auditId}/issues/items endpoint.
   *
   * Supports filtering by:
   * - `search`: full text search across snapshot title and description
   *
   * Results are sorted by snapshot creation date in descending order (newest first).
   *
   * Uses cursor-based pagination. To paginate:
   * 1. Make initial request with desired `pageSize`
   * 2. Check `results.pageInfo.hasNextPage`
   * 3. Use `results.pageInfo.endCursor` as `pageCursor` for next request
   */
  async listAuditSnapshots(
    request: operations.ListAuditSnapshotsRequest,
    options?: RequestOptions,
  ): Promise<components.PaginatedIssueSnapshotMetadataResponse> {
    return unwrapAsync(auditsListAuditSnapshots(
      this,
      request,
      options,
    ));
  }

  /**
   * Share information request list with customer
   *
   * @remarks
   * Shares the current information request list for an audit with the customer organization,
   * making it visible in their portal. This action allows the customer to see all information
   * requests that have been created for their audit. Only IRL audits are supported.
   */
  async shareInformationRequestList(
    request: operations.ShareInformationRequestListRequest,
    options?: RequestOptions,
  ): Promise<components.Audit> {
    return unwrapAsync(auditsShareInformationRequestList(
      this,
      request,
      options,
    ));
  }
}
