/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import * as components from "../components/index.js";

export type CreateCommentForControlRequest = {
  auditId: string;
  controlId: string;
  addAuditControlCommentInput: components.AddAuditControlCommentInput;
};

/** @internal */
export type CreateCommentForControlRequest$Outbound = {
  auditId: string;
  controlId: string;
  AddAuditControlCommentInput: components.AddAuditControlCommentInput$Outbound;
};

/** @internal */
export const CreateCommentForControlRequest$outboundSchema: z.ZodType<
  CreateCommentForControlRequest$Outbound,
  z.ZodTypeDef,
  CreateCommentForControlRequest
> = z.object({
  auditId: z.string(),
  controlId: z.string(),
  addAuditControlCommentInput:
    components.AddAuditControlCommentInput$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    addAuditControlCommentInput: "AddAuditControlCommentInput",
  });
});

export function createCommentForControlRequestToJSON(
  createCommentForControlRequest: CreateCommentForControlRequest,
): string {
  return JSON.stringify(
    CreateCommentForControlRequest$outboundSchema.parse(
      createCommentForControlRequest,
    ),
  );
}
