/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import * as components from "../components/index.js";

export type CreateCustomControlRequest = {
  auditId: string;
  createCustomControlInput: components.CreateCustomControlInput;
};

/** @internal */
export type CreateCustomControlRequest$Outbound = {
  auditId: string;
  CreateCustomControlInput: components.CreateCustomControlInput$Outbound;
};

/** @internal */
export const CreateCustomControlRequest$outboundSchema: z.ZodType<
  CreateCustomControlRequest$Outbound,
  z.ZodTypeDef,
  CreateCustomControlRequest
> = z.object({
  auditId: z.string(),
  createCustomControlInput: components.CreateCustomControlInput$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    createCustomControlInput: "CreateCustomControlInput",
  });
});

export function createCustomControlRequestToJSON(
  createCustomControlRequest: CreateCustomControlRequest,
): string {
  return JSON.stringify(
    CreateCustomControlRequest$outboundSchema.parse(createCustomControlRequest),
  );
}
