/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import * as components from "../components/index.js";

export type CreateCommentForInformationRequestRequest = {
  auditId: string;
  requestId: string;
  addInformationRequestCommentInput:
    components.AddInformationRequestCommentInput;
};

/** @internal */
export type CreateCommentForInformationRequestRequest$Outbound = {
  auditId: string;
  requestId: string;
  AddInformationRequestCommentInput:
    components.AddInformationRequestCommentInput$Outbound;
};

/** @internal */
export const CreateCommentForInformationRequestRequest$outboundSchema:
  z.ZodType<
    CreateCommentForInformationRequestRequest$Outbound,
    z.ZodTypeDef,
    CreateCommentForInformationRequestRequest
  > = z.object({
    auditId: z.string(),
    requestId: z.string(),
    addInformationRequestCommentInput:
      components.AddInformationRequestCommentInput$outboundSchema,
  }).transform((v) => {
    return remap$(v, {
      addInformationRequestCommentInput: "AddInformationRequestCommentInput",
    });
  });

export function createCommentForInformationRequestRequestToJSON(
  createCommentForInformationRequestRequest:
    CreateCommentForInformationRequestRequest,
): string {
  return JSON.stringify(
    CreateCommentForInformationRequestRequest$outboundSchema.parse(
      createCommentForInformationRequestRequest,
    ),
  );
}
