/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import * as components from "../components/index.js";

export type CreateCustomEvidenceRequestRequest = {
  auditId: string;
  createCustomEvidenceRequestInput: components.CreateCustomEvidenceRequestInput;
};

/** @internal */
export type CreateCustomEvidenceRequestRequest$Outbound = {
  auditId: string;
  CreateCustomEvidenceRequestInput:
    components.CreateCustomEvidenceRequestInput$Outbound;
};

/** @internal */
export const CreateCustomEvidenceRequestRequest$outboundSchema: z.ZodType<
  CreateCustomEvidenceRequestRequest$Outbound,
  z.ZodTypeDef,
  CreateCustomEvidenceRequestRequest
> = z.object({
  auditId: z.string(),
  createCustomEvidenceRequestInput:
    components.CreateCustomEvidenceRequestInput$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    createCustomEvidenceRequestInput: "CreateCustomEvidenceRequestInput",
  });
});

export function createCustomEvidenceRequestRequestToJSON(
  createCustomEvidenceRequestRequest: CreateCustomEvidenceRequestRequest,
): string {
  return JSON.stringify(
    CreateCustomEvidenceRequestRequest$outboundSchema.parse(
      createCustomEvidenceRequestRequest,
    ),
  );
}
