/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import * as components from "../components/index.js";

export type DeleteCommentForInformationRequestRequest = {
  auditId: string;
  requestId: string;
  commentId: string;
  deleteInformationRequestCommentInput:
    components.DeleteInformationRequestCommentInput;
};

/** @internal */
export type DeleteCommentForInformationRequestRequest$Outbound = {
  auditId: string;
  requestId: string;
  commentId: string;
  DeleteInformationRequestCommentInput:
    components.DeleteInformationRequestCommentInput$Outbound;
};

/** @internal */
export const DeleteCommentForInformationRequestRequest$outboundSchema:
  z.ZodType<
    DeleteCommentForInformationRequestRequest$Outbound,
    z.ZodTypeDef,
    DeleteCommentForInformationRequestRequest
  > = z.object({
    auditId: z.string(),
    requestId: z.string(),
    commentId: z.string(),
    deleteInformationRequestCommentInput:
      components.DeleteInformationRequestCommentInput$outboundSchema,
  }).transform((v) => {
    return remap$(v, {
      deleteInformationRequestCommentInput:
        "DeleteInformationRequestCommentInput",
    });
  });

export function deleteCommentForInformationRequestRequestToJSON(
  deleteCommentForInformationRequestRequest:
    DeleteCommentForInformationRequestRequest,
): string {
  return JSON.stringify(
    DeleteCommentForInformationRequestRequest$outboundSchema.parse(
      deleteCommentForInformationRequestRequest,
    ),
  );
}
