/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import * as components from "../components/index.js";

export type DeleteCommentForControlRequest = {
  auditId: string;
  controlId: string;
  commentId: string;
  deleteAuditControlCommentInput: components.DeleteAuditControlCommentInput;
};

/** @internal */
export type DeleteCommentForControlRequest$Outbound = {
  auditId: string;
  controlId: string;
  commentId: string;
  DeleteAuditControlCommentInput:
    components.DeleteAuditControlCommentInput$Outbound;
};

/** @internal */
export const DeleteCommentForControlRequest$outboundSchema: z.ZodType<
  DeleteCommentForControlRequest$Outbound,
  z.ZodTypeDef,
  DeleteCommentForControlRequest
> = z.object({
  auditId: z.string(),
  controlId: z.string(),
  commentId: z.string(),
  deleteAuditControlCommentInput:
    components.DeleteAuditControlCommentInput$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    deleteAuditControlCommentInput: "DeleteAuditControlCommentInput",
  });
});

export function deleteCommentForControlRequestToJSON(
  deleteCommentForControlRequest: DeleteCommentForControlRequest,
): string {
  return JSON.stringify(
    DeleteCommentForControlRequest$outboundSchema.parse(
      deleteCommentForControlRequest,
    ),
  );
}
