/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import * as components from "../components/index.js";

export type FlagInformationRequestEvidenceRequest = {
  auditId: string;
  requestId: string;
  flagInformationRequestEvidenceInput:
    components.FlagInformationRequestEvidenceInput;
};

/** @internal */
export type FlagInformationRequestEvidenceRequest$Outbound = {
  auditId: string;
  requestId: string;
  FlagInformationRequestEvidenceInput:
    components.FlagInformationRequestEvidenceInput$Outbound;
};

/** @internal */
export const FlagInformationRequestEvidenceRequest$outboundSchema: z.ZodType<
  FlagInformationRequestEvidenceRequest$Outbound,
  z.ZodTypeDef,
  FlagInformationRequestEvidenceRequest
> = z.object({
  auditId: z.string(),
  requestId: z.string(),
  flagInformationRequestEvidenceInput:
    components.FlagInformationRequestEvidenceInput$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    flagInformationRequestEvidenceInput: "FlagInformationRequestEvidenceInput",
  });
});

export function flagInformationRequestEvidenceRequestToJSON(
  flagInformationRequestEvidenceRequest: FlagInformationRequestEvidenceRequest,
): string {
  return JSON.stringify(
    FlagInformationRequestEvidenceRequest$outboundSchema.parse(
      flagInformationRequestEvidenceRequest,
    ),
  );
}
