/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type GetAuditEvidenceCommentRequest = {
  auditId: string;
  auditEvidenceId: string;
  commentId: string;
};

/** @internal */
export type GetAuditEvidenceCommentRequest$Outbound = {
  auditId: string;
  auditEvidenceId: string;
  commentId: string;
};

/** @internal */
export const GetAuditEvidenceCommentRequest$outboundSchema: z.ZodType<
  GetAuditEvidenceCommentRequest$Outbound,
  z.ZodTypeDef,
  GetAuditEvidenceCommentRequest
> = z.object({
  auditId: z.string(),
  auditEvidenceId: z.string(),
  commentId: z.string(),
});

export function getAuditEvidenceCommentRequestToJSON(
  getAuditEvidenceCommentRequest: GetAuditEvidenceCommentRequest,
): string {
  return JSON.stringify(
    GetAuditEvidenceCommentRequest$outboundSchema.parse(
      getAuditEvidenceCommentRequest,
    ),
  );
}
