/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type GetAuditRequest = {
  auditId: string;
};

/** @internal */
export type GetAuditRequest$Outbound = {
  auditId: string;
};

/** @internal */
export const GetAuditRequest$outboundSchema: z.ZodType<
  GetAuditRequest$Outbound,
  z.ZodTypeDef,
  GetAuditRequest
> = z.object({
  auditId: z.string(),
});

export function getAuditRequestToJSON(
  getAuditRequest: GetAuditRequest,
): string {
  return JSON.stringify(GetAuditRequest$outboundSchema.parse(getAuditRequest));
}
