/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type GetCommentForInformationRequestRequest = {
  auditId: string;
  requestId: string;
  commentId: string;
};

/** @internal */
export type GetCommentForInformationRequestRequest$Outbound = {
  auditId: string;
  requestId: string;
  commentId: string;
};

/** @internal */
export const GetCommentForInformationRequestRequest$outboundSchema: z.ZodType<
  GetCommentForInformationRequestRequest$Outbound,
  z.ZodTypeDef,
  GetCommentForInformationRequestRequest
> = z.object({
  auditId: z.string(),
  requestId: z.string(),
  commentId: z.string(),
});

export function getCommentForInformationRequestRequestToJSON(
  getCommentForInformationRequestRequest:
    GetCommentForInformationRequestRequest,
): string {
  return JSON.stringify(
    GetCommentForInformationRequestRequest$outboundSchema.parse(
      getCommentForInformationRequestRequest,
    ),
  );
}
