/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type GetInformationRequestEvidenceRequest = {
  auditId: string;
  requestId: string;
  evidenceId: string;
};

/** @internal */
export type GetInformationRequestEvidenceRequest$Outbound = {
  auditId: string;
  requestId: string;
  evidenceId: string;
};

/** @internal */
export const GetInformationRequestEvidenceRequest$outboundSchema: z.ZodType<
  GetInformationRequestEvidenceRequest$Outbound,
  z.ZodTypeDef,
  GetInformationRequestEvidenceRequest
> = z.object({
  auditId: z.string(),
  requestId: z.string(),
  evidenceId: z.string(),
});

export function getInformationRequestEvidenceRequestToJSON(
  getInformationRequestEvidenceRequest: GetInformationRequestEvidenceRequest,
): string {
  return JSON.stringify(
    GetInformationRequestEvidenceRequest$outboundSchema.parse(
      getInformationRequestEvidenceRequest,
    ),
  );
}
