/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type GetInformationRequestRequest = {
  auditId: string;
  requestId: string;
};

/** @internal */
export type GetInformationRequestRequest$Outbound = {
  auditId: string;
  requestId: string;
};

/** @internal */
export const GetInformationRequestRequest$outboundSchema: z.ZodType<
  GetInformationRequestRequest$Outbound,
  z.ZodTypeDef,
  GetInformationRequestRequest
> = z.object({
  auditId: z.string(),
  requestId: z.string(),
});

export function getInformationRequestRequestToJSON(
  getInformationRequestRequest: GetInformationRequestRequest,
): string {
  return JSON.stringify(
    GetInformationRequestRequest$outboundSchema.parse(
      getInformationRequestRequest,
    ),
  );
}
