/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type GetOrganizationInformationRequest = {
  /**
   * The audit ID
   */
  auditId: string;
};

/** @internal */
export type GetOrganizationInformationRequest$Outbound = {
  auditId: string;
};

/** @internal */
export const GetOrganizationInformationRequest$outboundSchema: z.ZodType<
  GetOrganizationInformationRequest$Outbound,
  z.ZodTypeDef,
  GetOrganizationInformationRequest
> = z.object({
  auditId: z.string(),
});

export function getOrganizationInformationRequestToJSON(
  getOrganizationInformationRequest: GetOrganizationInformationRequest,
): string {
  return JSON.stringify(
    GetOrganizationInformationRequest$outboundSchema.parse(
      getOrganizationInformationRequest,
    ),
  );
}
