/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type GetOrganizationNotificationsRequest = {
  /**
   * The audit ID
   */
  auditId: string;
};

/** @internal */
export type GetOrganizationNotificationsRequest$Outbound = {
  auditId: string;
};

/** @internal */
export const GetOrganizationNotificationsRequest$outboundSchema: z.ZodType<
  GetOrganizationNotificationsRequest$Outbound,
  z.ZodTypeDef,
  GetOrganizationNotificationsRequest
> = z.object({
  auditId: z.string(),
});

export function getOrganizationNotificationsRequestToJSON(
  getOrganizationNotificationsRequest: GetOrganizationNotificationsRequest,
): string {
  return JSON.stringify(
    GetOrganizationNotificationsRequest$outboundSchema.parse(
      getOrganizationNotificationsRequest,
    ),
  );
}
