/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type ListAuditsRequest = {
  pageSize?: number | undefined;
  pageCursor?: string | undefined;
  /**
   * Includes all audits that have changed since changedSinceDate.
   */
  changedSinceDate?: Date | undefined;
  /**
   * Includes only audits with no audit report uploaded
   */
  isActiveAudit?: boolean | undefined;
};

/** @internal */
export const ListAuditsRequest$inboundSchema: z.ZodType<
  ListAuditsRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  pageSize: z.number().int().default(10),
  pageCursor: z.string().optional(),
  changedSinceDate: z.string().datetime({ offset: true }).transform(v =>
    new Date(v)
  ).optional(),
  isActiveAudit: z.boolean().optional(),
});
/** @internal */
export type ListAuditsRequest$Outbound = {
  pageSize: number;
  pageCursor?: string | undefined;
  changedSinceDate?: string | undefined;
  isActiveAudit?: boolean | undefined;
};

/** @internal */
export const ListAuditsRequest$outboundSchema: z.ZodType<
  ListAuditsRequest$Outbound,
  z.ZodTypeDef,
  ListAuditsRequest
> = z.object({
  pageSize: z.number().int().default(10),
  pageCursor: z.string().optional(),
  changedSinceDate: z.date().transform(v => v.toISOString()).optional(),
  isActiveAudit: z.boolean().optional(),
});

export function listAuditsRequestToJSON(
  listAuditsRequest: ListAuditsRequest,
): string {
  return JSON.stringify(
    ListAuditsRequest$outboundSchema.parse(listAuditsRequest),
  );
}
export function listAuditsRequestFromJSON(
  jsonString: string,
): SafeParseResult<ListAuditsRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListAuditsRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListAuditsRequest' from JSON`,
  );
}
