/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type ListAuditControlsRequest = {
  auditId: string;
  pageSize?: number | undefined;
  pageCursor?: string | undefined;
};

/** @internal */
export const ListAuditControlsRequest$inboundSchema: z.ZodType<
  ListAuditControlsRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  auditId: z.string(),
  pageSize: z.number().int().default(10),
  pageCursor: z.string().optional(),
});
/** @internal */
export type ListAuditControlsRequest$Outbound = {
  auditId: string;
  pageSize: number;
  pageCursor?: string | undefined;
};

/** @internal */
export const ListAuditControlsRequest$outboundSchema: z.ZodType<
  ListAuditControlsRequest$Outbound,
  z.ZodTypeDef,
  ListAuditControlsRequest
> = z.object({
  auditId: z.string(),
  pageSize: z.number().int().default(10),
  pageCursor: z.string().optional(),
});

export function listAuditControlsRequestToJSON(
  listAuditControlsRequest: ListAuditControlsRequest,
): string {
  return JSON.stringify(
    ListAuditControlsRequest$outboundSchema.parse(listAuditControlsRequest),
  );
}
export function listAuditControlsRequestFromJSON(
  jsonString: string,
): SafeParseResult<ListAuditControlsRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListAuditControlsRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListAuditControlsRequest' from JSON`,
  );
}
