/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type ListAuditSnapshotsRequest = {
  /**
   * The audit ID
   */
  auditId: string;
  /**
   * Maximum number of results per page (1-100, default 10)
   */
  pageSize?: number | undefined;
  /**
   * Pagination cursor from previous response
   */
  pageCursor?: string | undefined;
  /**
   * Search term for filtering by snapshot title and description
   */
  search?: string | undefined;
};

/** @internal */
export type ListAuditSnapshotsRequest$Outbound = {
  auditId: string;
  pageSize: number;
  pageCursor?: string | undefined;
  search?: string | undefined;
};

/** @internal */
export const ListAuditSnapshotsRequest$outboundSchema: z.ZodType<
  ListAuditSnapshotsRequest$Outbound,
  z.ZodTypeDef,
  ListAuditSnapshotsRequest
> = z.object({
  auditId: z.string(),
  pageSize: z.number().int().default(10),
  pageCursor: z.string().optional(),
  search: z.string().optional(),
});

export function listAuditSnapshotsRequestToJSON(
  listAuditSnapshotsRequest: ListAuditSnapshotsRequest,
): string {
  return JSON.stringify(
    ListAuditSnapshotsRequest$outboundSchema.parse(listAuditSnapshotsRequest),
  );
}
