/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import * as components from "../components/index.js";

export type ListMonitoredComputersInAuditScopeRequest = {
  auditId: string;
  pageSize?: number | undefined;
  pageCursor?: string | undefined;
  /**
   * Filters for monitored computers matching any status declared in the filter.
   */
  complianceStatusFilterMatchesAny?:
    | Array<components.ComputerStatusFilter>
    | undefined;
};

/** @internal */
export type ListMonitoredComputersInAuditScopeRequest$Outbound = {
  auditId: string;
  pageSize: number;
  pageCursor?: string | undefined;
  complianceStatusFilterMatchesAny?: Array<string> | undefined;
};

/** @internal */
export const ListMonitoredComputersInAuditScopeRequest$outboundSchema:
  z.ZodType<
    ListMonitoredComputersInAuditScopeRequest$Outbound,
    z.ZodTypeDef,
    ListMonitoredComputersInAuditScopeRequest
  > = z.object({
    auditId: z.string(),
    pageSize: z.number().int().default(10),
    pageCursor: z.string().optional(),
    complianceStatusFilterMatchesAny: z.array(
      components.ComputerStatusFilter$outboundSchema,
    ).optional(),
  });

export function listMonitoredComputersInAuditScopeRequestToJSON(
  listMonitoredComputersInAuditScopeRequest:
    ListMonitoredComputersInAuditScopeRequest,
): string {
  return JSON.stringify(
    ListMonitoredComputersInAuditScopeRequest$outboundSchema.parse(
      listMonitoredComputersInAuditScopeRequest,
    ),
  );
}
