/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import * as components from "../components/index.js";

export type ListIntegrationsRequest = {
  /**
   * The audit ID
   */
  auditId: string;
  /**
   * Maximum number of results per page (1-100, default 10)
   */
  pageSize?: number | undefined;
  /**
   * Pagination cursor from previous response
   */
  pageCursor?: string | undefined;
  /**
   * Search term for filtering by integration name
   */
  search?: string | undefined;
  /**
   * Filter integrations by tag values
   */
  tagsMatchesAny?: Array<components.AuditIntegrationTag> | undefined;
  /**
   * Filter integrations by category values
   */
  categoriesMatchesAny?: Array<components.AuditIntegrationCategory> | undefined;
};

/** @internal */
export type ListIntegrationsRequest$Outbound = {
  auditId: string;
  pageSize: number;
  pageCursor?: string | undefined;
  search?: string | undefined;
  tagsMatchesAny?: Array<string> | undefined;
  categoriesMatchesAny?: Array<string> | undefined;
};

/** @internal */
export const ListIntegrationsRequest$outboundSchema: z.ZodType<
  ListIntegrationsRequest$Outbound,
  z.ZodTypeDef,
  ListIntegrationsRequest
> = z.object({
  auditId: z.string(),
  pageSize: z.number().int().default(10),
  pageCursor: z.string().optional(),
  search: z.string().optional(),
  tagsMatchesAny: z.array(components.AuditIntegrationTag$outboundSchema)
    .optional(),
  categoriesMatchesAny: z.array(
    components.AuditIntegrationCategory$outboundSchema,
  ).optional(),
});

export function listIntegrationsRequestToJSON(
  listIntegrationsRequest: ListIntegrationsRequest,
): string {
  return JSON.stringify(
    ListIntegrationsRequest$outboundSchema.parse(listIntegrationsRequest),
  );
}
