/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type ListRiskSnapshotsRequest = {
  /**
   * The audit ID
   */
  auditId: string;
  /**
   * Maximum number of results per page (1-100, default 10)
   */
  pageSize?: number | undefined;
  /**
   * Pagination cursor from previous response
   */
  pageCursor?: string | undefined;
};

/** @internal */
export type ListRiskSnapshotsRequest$Outbound = {
  auditId: string;
  pageSize: number;
  pageCursor?: string | undefined;
};

/** @internal */
export const ListRiskSnapshotsRequest$outboundSchema: z.ZodType<
  ListRiskSnapshotsRequest$Outbound,
  z.ZodTypeDef,
  ListRiskSnapshotsRequest
> = z.object({
  auditId: z.string(),
  pageSize: z.number().int().default(10),
  pageCursor: z.string().optional(),
});

export function listRiskSnapshotsRequestToJSON(
  listRiskSnapshotsRequest: ListRiskSnapshotsRequest,
): string {
  return JSON.stringify(
    ListRiskSnapshotsRequest$outboundSchema.parse(listRiskSnapshotsRequest),
  );
}
