/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type ListAuditCommentsRequest = {
  auditId: string;
  pageSize?: number | undefined;
  pageCursor?: string | undefined;
  /**
   * Includes all comments that have changed since changedSinceDate.
   */
  changedSinceDate?: Date | undefined;
};

/** @internal */
export const ListAuditCommentsRequest$inboundSchema: z.ZodType<
  ListAuditCommentsRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  auditId: z.string(),
  pageSize: z.number().int().default(10),
  pageCursor: z.string().optional(),
  changedSinceDate: z.string().datetime({ offset: true }).transform(v =>
    new Date(v)
  ).optional(),
});
/** @internal */
export type ListAuditCommentsRequest$Outbound = {
  auditId: string;
  pageSize: number;
  pageCursor?: string | undefined;
  changedSinceDate?: string | undefined;
};

/** @internal */
export const ListAuditCommentsRequest$outboundSchema: z.ZodType<
  ListAuditCommentsRequest$Outbound,
  z.ZodTypeDef,
  ListAuditCommentsRequest
> = z.object({
  auditId: z.string(),
  pageSize: z.number().int().default(10),
  pageCursor: z.string().optional(),
  changedSinceDate: z.date().transform(v => v.toISOString()).optional(),
});

export function listAuditCommentsRequestToJSON(
  listAuditCommentsRequest: ListAuditCommentsRequest,
): string {
  return JSON.stringify(
    ListAuditCommentsRequest$outboundSchema.parse(listAuditCommentsRequest),
  );
}
export function listAuditCommentsRequestFromJSON(
  jsonString: string,
): SafeParseResult<ListAuditCommentsRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListAuditCommentsRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListAuditCommentsRequest' from JSON`,
  );
}
