/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type ListInformationRequestsRequest = {
  auditId: string;
  /**
   * Maximum number of information requests to return per page.
   */
  pageSize?: number | undefined;
  /**
   * Pagination cursor from a previous response. Provide to fetch the next page of results.
   */
  pageCursor?: string | undefined;
  /**
   * Includes all information requests that have changed since changedSinceDate.
   *
   * @remarks
   * Considers creationDate, modificationDate, and deletionDate timestamps when determining changes.
   * Does not include requests whose only change is the derived `segmentIds`
   * projection after an audit-scope change.
   */
  changedSinceDate?: Date | undefined;
  /**
   * Return requests whose stored segment assignment includes any of these
   *
   * @remarks
   * IDs (OR). Omit to return all. A match can still come back with
   * `segmentIds: []` if the stored ID is no longer in the audit's scope.
   */
  segmentIdsMatchesAny?: Array<string> | undefined;
};

/** @internal */
export type ListInformationRequestsRequest$Outbound = {
  auditId: string;
  pageSize: number;
  pageCursor?: string | undefined;
  changedSinceDate?: string | undefined;
  segmentIdsMatchesAny?: Array<string> | undefined;
};

/** @internal */
export const ListInformationRequestsRequest$outboundSchema: z.ZodType<
  ListInformationRequestsRequest$Outbound,
  z.ZodTypeDef,
  ListInformationRequestsRequest
> = z.object({
  auditId: z.string(),
  pageSize: z.number().int().default(10),
  pageCursor: z.string().optional(),
  changedSinceDate: z.date().transform(v => v.toISOString()).optional(),
  segmentIdsMatchesAny: z.array(z.string()).optional(),
});

export function listInformationRequestsRequestToJSON(
  listInformationRequestsRequest: ListInformationRequestsRequest,
): string {
  return JSON.stringify(
    ListInformationRequestsRequest$outboundSchema.parse(
      listInformationRequestsRequest,
    ),
  );
}
