/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import * as components from "../components/index.js";

export type ListCodeChangesRequest = {
  /**
   * The audit ID
   */
  auditId: string;
  /**
   * Maximum number of results per page (1-100, default 10)
   */
  pageSize?: number | undefined;
  /**
   * Pagination cursor from previous response
   */
  pageCursor?: string | undefined;
  /**
   * Search term for filtering by code change title or repository name
   */
  search?: string | undefined;
  /**
   * Filter code changes by version control source (accepted values: github, gitlab, bitbucket, azuredevops)
   */
  sourcesMatchesAny?: Array<components.ApiCodeChangeSource> | undefined;
  /**
   * Filter code changes closed on or after this date (ISO 8601)
   */
  closedAfterDate?: Date | undefined;
  /**
   * Filter code changes closed on or before this date (ISO 8601)
   */
  closedBeforeDate?: Date | undefined;
};

/** @internal */
export type ListCodeChangesRequest$Outbound = {
  auditId: string;
  pageSize: number;
  pageCursor?: string | undefined;
  search?: string | undefined;
  sourcesMatchesAny?: Array<string> | undefined;
  closedAfterDate?: string | undefined;
  closedBeforeDate?: string | undefined;
};

/** @internal */
export const ListCodeChangesRequest$outboundSchema: z.ZodType<
  ListCodeChangesRequest$Outbound,
  z.ZodTypeDef,
  ListCodeChangesRequest
> = z.object({
  auditId: z.string(),
  pageSize: z.number().int().default(10),
  pageCursor: z.string().optional(),
  search: z.string().optional(),
  sourcesMatchesAny: z.array(components.ApiCodeChangeSource$outboundSchema)
    .optional(),
  closedAfterDate: z.date().transform(v => v.toISOString()).optional(),
  closedBeforeDate: z.date().transform(v => v.toISOString()).optional(),
});

export function listCodeChangesRequestToJSON(
  listCodeChangesRequest: ListCodeChangesRequest,
): string {
  return JSON.stringify(
    ListCodeChangesRequest$outboundSchema.parse(listCodeChangesRequest),
  );
}
