/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type ListAuditEvidenceRequest = {
  auditId: string;
  pageSize?: number | undefined;
  pageCursor?: string | undefined;
  /**
   * Includes all audit evidence that have changed since changedSinceDate.
   */
  changedSinceDate?: Date | undefined;
};

/** @internal */
export type ListAuditEvidenceRequest$Outbound = {
  auditId: string;
  pageSize: number;
  pageCursor?: string | undefined;
  changedSinceDate?: string | undefined;
};

/** @internal */
export const ListAuditEvidenceRequest$outboundSchema: z.ZodType<
  ListAuditEvidenceRequest$Outbound,
  z.ZodTypeDef,
  ListAuditEvidenceRequest
> = z.object({
  auditId: z.string(),
  pageSize: z.number().int().default(10),
  pageCursor: z.string().optional(),
  changedSinceDate: z.date().transform(v => v.toISOString()).optional(),
});

export function listAuditEvidenceRequestToJSON(
  listAuditEvidenceRequest: ListAuditEvidenceRequest,
): string {
  return JSON.stringify(
    ListAuditEvidenceRequest$outboundSchema.parse(listAuditEvidenceRequest),
  );
}
