/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type ListCommentsForControlRequest = {
  auditId: string;
  controlId: string;
  /**
   * Maximum number of comments to return per page.
   */
  pageSize?: number | undefined;
  /**
   * Pagination cursor from a previous response. Provide to fetch the next page of comments.
   */
  pageCursor?: string | undefined;
  /**
   * Includes all comments that have changed since changedSinceDate.
   *
   * @remarks
   * Considers creationDate, modificationDate, and deletionDate timestamps when determining changes.
   */
  changedSinceDate?: Date | undefined;
};

/** @internal */
export type ListCommentsForControlRequest$Outbound = {
  auditId: string;
  controlId: string;
  pageSize: number;
  pageCursor?: string | undefined;
  changedSinceDate?: string | undefined;
};

/** @internal */
export const ListCommentsForControlRequest$outboundSchema: z.ZodType<
  ListCommentsForControlRequest$Outbound,
  z.ZodTypeDef,
  ListCommentsForControlRequest
> = z.object({
  auditId: z.string(),
  controlId: z.string(),
  pageSize: z.number().int().default(10),
  pageCursor: z.string().optional(),
  changedSinceDate: z.date().transform(v => v.toISOString()).optional(),
});

export function listCommentsForControlRequestToJSON(
  listCommentsForControlRequest: ListCommentsForControlRequest,
): string {
  return JSON.stringify(
    ListCommentsForControlRequest$outboundSchema.parse(
      listCommentsForControlRequest,
    ),
  );
}
