/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type ListAuditIssuesRequest = {
  /**
   * The audit ID
   */
  auditId: string;
  /**
   * Maximum number of results per page (1-100, default 10)
   */
  pageSize?: number | undefined;
  /**
   * Pagination cursor from previous response
   */
  pageCursor?: string | undefined;
  /**
   * Search term for filtering by issue title and description
   */
  search?: string | undefined;
  /**
   * Filter issues to specific snapshots by snapshot ID
   */
  snapshotIdMatchesAny?: Array<string> | undefined;
};

/** @internal */
export type ListAuditIssuesRequest$Outbound = {
  auditId: string;
  pageSize: number;
  pageCursor?: string | undefined;
  search?: string | undefined;
  snapshotIdMatchesAny?: Array<string> | undefined;
};

/** @internal */
export const ListAuditIssuesRequest$outboundSchema: z.ZodType<
  ListAuditIssuesRequest$Outbound,
  z.ZodTypeDef,
  ListAuditIssuesRequest
> = z.object({
  auditId: z.string(),
  pageSize: z.number().int().default(10),
  pageCursor: z.string().optional(),
  search: z.string().optional(),
  snapshotIdMatchesAny: z.array(z.string()).optional(),
});

export function listAuditIssuesRequestToJSON(
  listAuditIssuesRequest: ListAuditIssuesRequest,
): string {
  return JSON.stringify(
    ListAuditIssuesRequest$outboundSchema.parse(listAuditIssuesRequest),
  );
}
