/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type ListInformationRequestsForControlRequest = {
  auditId: string;
  controlId: string;
  /**
   * Maximum number of information requests to return per page.
   */
  pageSize?: number | undefined;
  /**
   * Pagination cursor from a previous response. Provide to fetch the next page of results.
   */
  pageCursor?: string | undefined;
};

/** @internal */
export type ListInformationRequestsForControlRequest$Outbound = {
  auditId: string;
  controlId: string;
  pageSize: number;
  pageCursor?: string | undefined;
};

/** @internal */
export const ListInformationRequestsForControlRequest$outboundSchema: z.ZodType<
  ListInformationRequestsForControlRequest$Outbound,
  z.ZodTypeDef,
  ListInformationRequestsForControlRequest
> = z.object({
  auditId: z.string(),
  controlId: z.string(),
  pageSize: z.number().int().default(10),
  pageCursor: z.string().optional(),
});

export function listInformationRequestsForControlRequestToJSON(
  listInformationRequestsForControlRequest:
    ListInformationRequestsForControlRequest,
): string {
  return JSON.stringify(
    ListInformationRequestsForControlRequest$outboundSchema.parse(
      listInformationRequestsForControlRequest,
    ),
  );
}
