/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type ListAuditControlsRequest = {
  auditId: string;
  pageSize?: number | undefined;
  pageCursor?: string | undefined;
  /**
   * Filter controls whose externalId matches any of the provided values (exact, case-sensitive match).
   */
  externalIdMatchesAny?: Array<string> | undefined;
};

/** @internal */
export type ListAuditControlsRequest$Outbound = {
  auditId: string;
  pageSize: number;
  pageCursor?: string | undefined;
  externalIdMatchesAny?: Array<string> | undefined;
};

/** @internal */
export const ListAuditControlsRequest$outboundSchema: z.ZodType<
  ListAuditControlsRequest$Outbound,
  z.ZodTypeDef,
  ListAuditControlsRequest
> = z.object({
  auditId: z.string(),
  pageSize: z.number().int().default(10),
  pageCursor: z.string().optional(),
  externalIdMatchesAny: z.array(z.string()).optional(),
});

export function listAuditControlsRequestToJSON(
  listAuditControlsRequest: ListAuditControlsRequest,
): string {
  return JSON.stringify(
    ListAuditControlsRequest$outboundSchema.parse(listAuditControlsRequest),
  );
}
