/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import * as components from "../components/index.js";

export type UpdateAuditEvidenceRequest = {
  auditId: string;
  auditEvidenceId: string;
  auditEvidenceUpdateInput: components.AuditEvidenceUpdateInput;
};

/** @internal */
export type UpdateAuditEvidenceRequest$Outbound = {
  auditId: string;
  auditEvidenceId: string;
  AuditEvidenceUpdateInput: components.AuditEvidenceUpdateInput$Outbound;
};

/** @internal */
export const UpdateAuditEvidenceRequest$outboundSchema: z.ZodType<
  UpdateAuditEvidenceRequest$Outbound,
  z.ZodTypeDef,
  UpdateAuditEvidenceRequest
> = z.object({
  auditId: z.string(),
  auditEvidenceId: z.string(),
  auditEvidenceUpdateInput: components.AuditEvidenceUpdateInput$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    auditEvidenceUpdateInput: "AuditEvidenceUpdateInput",
  });
});

export function updateAuditEvidenceRequestToJSON(
  updateAuditEvidenceRequest: UpdateAuditEvidenceRequest,
): string {
  return JSON.stringify(
    UpdateAuditEvidenceRequest$outboundSchema.parse(updateAuditEvidenceRequest),
  );
}
