/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import * as components from "../components/index.js";

export type UpdateInformationRequestRequest = {
  auditId: string;
  requestId: string;
  partialUpdateInformationRequest: components.PartialUpdateInformationRequest;
};

/** @internal */
export type UpdateInformationRequestRequest$Outbound = {
  auditId: string;
  requestId: string;
  PartialUpdateInformationRequest:
    components.PartialUpdateInformationRequest$Outbound;
};

/** @internal */
export const UpdateInformationRequestRequest$outboundSchema: z.ZodType<
  UpdateInformationRequestRequest$Outbound,
  z.ZodTypeDef,
  UpdateInformationRequestRequest
> = z.object({
  auditId: z.string(),
  requestId: z.string(),
  partialUpdateInformationRequest:
    components.PartialUpdateInformationRequest$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    partialUpdateInformationRequest: "PartialUpdateInformationRequest",
  });
});

export function updateInformationRequestRequestToJSON(
  updateInformationRequestRequest: UpdateInformationRequestRequest,
): string {
  return JSON.stringify(
    UpdateInformationRequestRequest$outboundSchema.parse(
      updateInformationRequestRequest,
    ),
  );
}
