/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import * as components from "../components/index.js";

export type UpsertAssessmentForControlRequest = {
  auditId: string;
  controlId: string;
  upsertAuditControlAssessmentInput:
    components.UpsertAuditControlAssessmentInput;
};

/** @internal */
export type UpsertAssessmentForControlRequest$Outbound = {
  auditId: string;
  controlId: string;
  UpsertAuditControlAssessmentInput:
    components.UpsertAuditControlAssessmentInput$Outbound;
};

/** @internal */
export const UpsertAssessmentForControlRequest$outboundSchema: z.ZodType<
  UpsertAssessmentForControlRequest$Outbound,
  z.ZodTypeDef,
  UpsertAssessmentForControlRequest
> = z.object({
  auditId: z.string(),
  controlId: z.string(),
  upsertAuditControlAssessmentInput:
    components.UpsertAuditControlAssessmentInput$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    upsertAuditControlAssessmentInput: "UpsertAuditControlAssessmentInput",
  });
});

export function upsertAssessmentForControlRequestToJSON(
  upsertAssessmentForControlRequest: UpsertAssessmentForControlRequest,
): string {
  return JSON.stringify(
    UpsertAssessmentForControlRequest$outboundSchema.parse(
      upsertAssessmentForControlRequest,
    ),
  );
}
