/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

/**
 * Input for accepting evidence on an information request, indicating that
 *
 * @remarks
 * the submitted evidence meets requirements. This changes the request's
 * approvalStatus to an approved state and creates an activity log entry.
 */
export type AcceptInformationRequestEvidenceInput = {
  /**
   * Email of the auditor accepting the evidence.
   *
   * @remarks
   * Must match an existing Vanta user who belongs to the audit firm making the API request.
   */
  auditorEmail: string;
};

/** @internal */
export type AcceptInformationRequestEvidenceInput$Outbound = {
  auditorEmail: string;
};

/** @internal */
export const AcceptInformationRequestEvidenceInput$outboundSchema: z.ZodType<
  AcceptInformationRequestEvidenceInput$Outbound,
  z.ZodTypeDef,
  AcceptInformationRequestEvidenceInput
> = z.object({
  auditorEmail: z.string(),
});

export function acceptInformationRequestEvidenceInputToJSON(
  acceptInformationRequestEvidenceInput: AcceptInformationRequestEvidenceInput,
): string {
  return JSON.stringify(
    AcceptInformationRequestEvidenceInput$outboundSchema.parse(
      acceptInformationRequestEvidenceInput,
    ),
  );
}
