/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * An account access service (identity provider, access credential, or external application)
 *
 * @remarks
 * connected to the organization.
 *
 * These represent credentials for integrations like Okta, Azure AD,
 * Google Workspace, etc. that provide identity and access management
 * data for personnel, as well as external applications that provide
 * received user accounts.
 */
export type AccountAccessService = {
  /**
   * Unique identifier for the service.
   */
  id: string;
  /**
   * Display name of the service shown to users.
   */
  credentialDisplayName: string;
  /**
   * The service name or integration ID.
   */
  service: string;
  /**
   * Sub-account identifier for multi-account integrations, or null if not applicable.
   */
  subAccountId: string | null;
};

/** @internal */
export const AccountAccessService$inboundSchema: z.ZodType<
  AccountAccessService,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
  credentialDisplayName: z.string(),
  service: z.string(),
  subAccountId: z.nullable(z.string()),
});

export function accountAccessServiceFromJSON(
  jsonString: string,
): SafeParseResult<AccountAccessService, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AccountAccessService$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AccountAccessService' from JSON`,
  );
}
