/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

/**
 * Comments enable auditors and customers to collaborate on a control within an
 *
 * @remarks
 * audit. All comments are immediately visible to authorized parties once created.
 */
export type AddAuditControlCommentInput = {
  /**
   * The text content of the comment.
   *
   * @remarks
   * Must be at least 1 character. Can include questions, clarifications,
   * or explanations related to the control.
   */
  text: string;
  /**
   * Email address of the comment author.
   *
   * @remarks
   * Must match an existing Vanta user who belongs to the audit firm making the API request.
   * This email uniquely identifies the author across systems.
   */
  email: string;
  /**
   * Timestamp when the comment was created in the external audit management system.
   *
   * @remarks
   * This allows synchronizing comment timestamps from external systems.
   * Format: ISO 8601 UTC timestamp.
   */
  creationDate: Date;
};

/** @internal */
export type AddAuditControlCommentInput$Outbound = {
  text: string;
  email: string;
  creationDate: string;
};

/** @internal */
export const AddAuditControlCommentInput$outboundSchema: z.ZodType<
  AddAuditControlCommentInput$Outbound,
  z.ZodTypeDef,
  AddAuditControlCommentInput
> = z.object({
  text: z.string(),
  email: z.string(),
  creationDate: z.date().transform(v => v.toISOString()),
});

export function addAuditControlCommentInputToJSON(
  addAuditControlCommentInput: AddAuditControlCommentInput,
): string {
  return JSON.stringify(
    AddAuditControlCommentInput$outboundSchema.parse(
      addAuditControlCommentInput,
    ),
  );
}
