/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type AddAuditorInput = {
  /**
   * Email of the new user.
   */
  email: string;
  /**
   * First name of the new user.
   */
  givenName: string;
  /**
   * Last name of the new user.
   */
  familyName: string;
};

/** @internal */
export type AddAuditorInput$Outbound = {
  email: string;
  givenName: string;
  familyName: string;
};

/** @internal */
export const AddAuditorInput$outboundSchema: z.ZodType<
  AddAuditorInput$Outbound,
  z.ZodTypeDef,
  AddAuditorInput
> = z.object({
  email: z.string(),
  givenName: z.string(),
  familyName: z.string(),
});

export function addAuditorInputToJSON(
  addAuditorInput: AddAuditorInput,
): string {
  return JSON.stringify(AddAuditorInput$outboundSchema.parse(addAuditorInput));
}
