/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type AddCommentInput = {
  /**
   * Text value of the comment
   */
  text: string;
  /**
   * Email of author. Must match an existing Vanta user and the user must exist under the Audit Firm who is making the API request
   */
  email: string;
  /**
   * When the comment was created in the external system
   */
  creationDate: Date;
};

/** @internal */
export type AddCommentInput$Outbound = {
  text: string;
  email: string;
  creationDate: string;
};

/** @internal */
export const AddCommentInput$outboundSchema: z.ZodType<
  AddCommentInput$Outbound,
  z.ZodTypeDef,
  AddCommentInput
> = z.object({
  text: z.string(),
  email: z.string(),
  creationDate: z.date().transform(v => v.toISOString()),
});

export function addCommentInputToJSON(
  addCommentInput: AddCommentInput,
): string {
  return JSON.stringify(AddCommentInput$outboundSchema.parse(addCommentInput));
}
