/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

/**
 * Comments enable communication between auditors and customers about
 *
 * @remarks
 * evidence requirements and submissions. All comments are immediately
 * visible to both parties once created.
 */
export type AddInformationRequestCommentInput = {
  /**
   * The text content of the comment.
   *
   * @remarks
   * Must be at least 1 character. Can include questions, clarifications,
   * or explanations related to the information request.
   */
  text: string;
  /**
   * Email address of the comment author.
   *
   * @remarks
   * Must match an existing Vanta user who belongs to the audit firm making the API request.
   * This email uniquely identifies the author across systems.
   */
  email: string;
  /**
   * Timestamp when the comment was created in the external audit management system.
   *
   * @remarks
   * This allows synchronizing comment timestamps from external systems.
   * Format: ISO 8601 UTC timestamp.
   */
  creationDate: Date;
};

/** @internal */
export type AddInformationRequestCommentInput$Outbound = {
  text: string;
  email: string;
  creationDate: string;
};

/** @internal */
export const AddInformationRequestCommentInput$outboundSchema: z.ZodType<
  AddInformationRequestCommentInput$Outbound,
  z.ZodTypeDef,
  AddInformationRequestCommentInput
> = z.object({
  text: z.string(),
  email: z.string(),
  creationDate: z.date().transform(v => v.toISOString()),
});

export function addInformationRequestCommentInputToJSON(
  addInformationRequestCommentInput: AddInformationRequestCommentInput,
): string {
  return JSON.stringify(
    AddInformationRequestCommentInput$outboundSchema.parse(
      addInformationRequestCommentInput,
    ),
  );
}
