/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { ClosedEnum } from "../../types/enums.js";

export const AuditIntegrationTag = {
  Access: "ACCESS",
  Computers: "COMPUTERS",
  CustomResource: "CUSTOM_RESOURCE",
  DataLossPrevention: "DATA_LOSS_PREVENTION",
  Documents: "DOCUMENTS",
  DocumentUpload: "DOCUMENT_UPLOAD",
  Framework: "FRAMEWORK",
  Groups: "GROUPS",
  Inventory: "INVENTORY",
  Notifications: "NOTIFICATIONS",
  People: "PEOPLE",
  Policies: "POLICIES",
  SecurityAwarenessTraining: "SECURITY_AWARENESS_TRAINING",
  SecurityScannerAlerts: "SECURITY_SCANNER_ALERTS",
  Sso: "SSO",
  TaskCreation: "TASK_CREATION",
  TaskTracking: "TASK_TRACKING",
  TrustCenter: "TRUST_CENTER",
  VendorDiscovery: "VENDOR_DISCOVERY",
  VendorProcurement: "VENDOR_PROCUREMENT",
  Vulnerabilities: "VULNERABILITIES",
} as const;
export type AuditIntegrationTag = ClosedEnum<typeof AuditIntegrationTag>;

/** @internal */
export const AuditIntegrationTag$outboundSchema: z.ZodNativeEnum<
  typeof AuditIntegrationTag
> = z.nativeEnum(AuditIntegrationTag);
