/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { ClosedEnum } from "../../types/enums.js";

export const AuditIntegrationServiceCategory = {
  AtsMergeAccount: "ATS_MERGE_ACCOUNT",
  BackgroundCheckService: "BACKGROUND_CHECK_SERVICE",
  CloudProvider: "CLOUD_PROVIDER",
  CommunicationPlatform: "COMMUNICATION_PLATFORM",
  CrmMergeAccount: "CRM_MERGE_ACCOUNT",
  CrmPlatform: "CRM_PLATFORM",
  DatastoreProvider: "DATASTORE_PROVIDER",
  DataLossPrevention: "DATA_LOSS_PREVENTION",
  DataWarehouseProvider: "DATA_WAREHOUSE_PROVIDER",
  DocumentManagementTool: "DOCUMENT_MANAGEMENT_TOOL",
  EndpointSecurityTool: "ENDPOINT_SECURITY_TOOL",
  HrProvider: "HR_PROVIDER",
  IdentityProvider: "IDENTITY_PROVIDER",
  IncidentManagementTool: "INCIDENT_MANAGEMENT_TOOL",
  MobileDeviceManagementTool: "MOBILE_DEVICE_MANAGEMENT_TOOL",
  MonitoringService: "MONITORING_SERVICE",
  OtherIntegration: "OTHER_INTEGRATION",
  SecurityAwarenessTrainingProvider: "SECURITY_AWARENESS_TRAINING_PROVIDER",
  SecurityScannerAlerts: "SECURITY_SCANNER_ALERTS",
  TaskTracker: "TASK_TRACKER",
  VersionControlSystem: "VERSION_CONTROL_SYSTEM",
  VulnerabilityScanner: "VULNERABILITY_SCANNER",
} as const;
export type AuditIntegrationServiceCategory = ClosedEnum<
  typeof AuditIntegrationServiceCategory
>;

/** @internal */
export const AuditIntegrationServiceCategory$outboundSchema: z.ZodNativeEnum<
  typeof AuditIntegrationServiceCategory
> = z.nativeEnum(AuditIntegrationServiceCategory);
