/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { ClosedEnum } from "../../types/enums.js";

export const AuditSegmentKind = {
  Program: "PROGRAM",
  System: "SYSTEM",
} as const;
export type AuditSegmentKind = ClosedEnum<typeof AuditSegmentKind>;

/** @internal */
export const AuditSegmentKind$inboundSchema: z.ZodNativeEnum<
  typeof AuditSegmentKind
> = z.nativeEnum(AuditSegmentKind);
