/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * The framework reached through a segment.
 */
export type AuditSegmentFramework = {
  /**
   * The stable identifier of the framework (for example `soc2`).
   */
  id: string;
  /**
   * The human-readable framework name.
   */
  displayName: string;
  /**
   * The short framework name used in compact UI.
   */
  shortName: string;
};

/** @internal */
export const AuditSegmentFramework$inboundSchema: z.ZodType<
  AuditSegmentFramework,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
  displayName: z.string(),
  shortName: z.string(),
});

export function auditSegmentFrameworkFromJSON(
  jsonString: string,
): SafeParseResult<AuditSegmentFramework, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AuditSegmentFramework$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AuditSegmentFramework' from JSON`,
  );
}
