/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  AuditControlAssessment,
  AuditControlAssessment$inboundSchema,
} from "./auditcontrolassessment.js";
import { ControlSource, ControlSource$inboundSchema } from "./controlsource.js";
import { CustomField, CustomField$inboundSchema } from "./customfield.js";
import { Section, Section$inboundSchema } from "./section.js";

/**
 * The control's owner.
 */
export type Owner = {
  /**
   * Unique identifier for the person.
   */
  id: string;
  /**
   * Name of the person that is shown in product.
   */
  displayName: string;
  /**
   * Email address of the person.
   */
  emailAddress: string;
};

export type AuditorControl = {
  /**
   * The control's unique ID.
   */
  id: string;
  /**
   * The control's external ID.
   */
  externalId: string | null;
  /**
   * The control's name.
   */
  name: string;
  /**
   * The control's description.
   */
  description: string;
  source: ControlSource;
  /**
   * The security domains that the control belongs to.
   */
  domains: Array<string>;
  /**
   * The control's owner.
   */
  owner: Owner | null;
  /**
   * The control's GDPR role, if the control is a GDPR control.
   */
  role?: string | null | undefined;
  /**
   * The control's custom field values, if control custom fields is included in your Vanta instance.
   */
  customFields: Array<CustomField>;
  /**
   * When the control was created. Returns null for Vanta library controls.
   */
  creationDate: Date | null;
  /**
   * When the control was last modified. Returns null for Vanta library controls.
   */
  modificationDate: Date | null;
  /**
   * The report standard framework fulfilled by the control.
   *
   * @remarks
   * Incomplete once a control is in scope for more than one framework.
   *
   * @deprecated field: This will be removed in a future release, please migrate away from it as soon as possible.
   */
  framework: string;
  /**
   * Sections of a framework that this control satisfies
   */
  sections: Array<Section>;
  /**
   * Audit segments this control is in scope for. Empty when the control is
   *
   * @remarks
   * attached only by a direct link and has no catalog mapping on a
   * multi-program audit.
   */
  inScopeSegmentIds: Array<string>;
  /**
   * The auditor's assessments of this control, one per audit program segment the
   *
   * @remarks
   * control is in scope for (a multi-framework audit can have more than one).
   * Populated only for IRL audits when the assessment feature is enabled; empty
   * otherwise. Within an in-scope segment a control with no recorded assessment
   * coerces to `NOT_ASSESSED`; a segment the control is not in scope for
   * contributes no entry.
   */
  assessments: Array<AuditControlAssessment>;
};

/** @internal */
export const Owner$inboundSchema: z.ZodType<Owner, z.ZodTypeDef, unknown> = z
  .object({
    id: z.string(),
    displayName: z.string(),
    emailAddress: z.string(),
  });

export function ownerFromJSON(
  jsonString: string,
): SafeParseResult<Owner, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Owner$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Owner' from JSON`,
  );
}

/** @internal */
export const AuditorControl$inboundSchema: z.ZodType<
  AuditorControl,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
  externalId: z.nullable(z.string()),
  name: z.string(),
  description: z.string(),
  source: ControlSource$inboundSchema,
  domains: z.array(z.string()),
  owner: z.nullable(z.lazy(() => Owner$inboundSchema)),
  role: z.nullable(z.string()).optional(),
  customFields: z.array(CustomField$inboundSchema),
  creationDate: z.nullable(
    z.string().datetime({ offset: true }).transform(v => new Date(v)),
  ),
  modificationDate: z.nullable(
    z.string().datetime({ offset: true }).transform(v => new Date(v)),
  ),
  framework: z.string(),
  sections: z.array(Section$inboundSchema),
  inScopeSegmentIds: z.array(z.string()),
  assessments: z.array(AuditControlAssessment$inboundSchema),
});

export function auditorControlFromJSON(
  jsonString: string,
): SafeParseResult<AuditorControl, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AuditorControl$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AuditorControl' from JSON`,
  );
}
