/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import { AuditFocus, AuditFocus$inboundSchema } from "./auditfocus.js";

export type Audit = {
  /**
   * The unique identifier for the audit.
   */
  id: string;
  /**
   * The domain name of the customer organization being audited (e.g. vanta.com)
   */
  customerOrganizationName: string;
  /**
   * The human readable name of the customer organization being audited (e.g. Vanta)
   */
  customerDisplayName: string | null;
  /**
   * The uuid of the customer organization being audited
   */
  customerOrganizationId: string;
  /**
   * The start of the audit window. This is also when data collection for audit starts.
   */
  auditStartDate: Date;
  /**
   * The end of the audit window.
   */
  auditEndDate: Date;
  /**
   * Timestamp at which auditors gain access to the audit. Occurs before the audit window begins
   */
  earlyAccessStartsAt: Date | null;
  /**
   * The name of the framework for the audit
   */
  framework: string;
  /**
   * Emails of auditors with access to audit
   */
  allowAuditorEmails: Array<string>;
  /**
   * Set to true if all auditors in audit firm have access
   */
  allowAllAuditors: boolean;
  /**
   * Timestamp when the audit was deleted
   */
  deletionDate: Date | null;
  /**
   * Timestamp when the audit was created
   */
  creationDate: Date;
  /**
   * Timestamp when the audit was updated
   */
  modificationDate: Date | null;
  /**
   * Timestamp when the audit was marked completed, and report was uploaded
   */
  completionDate: Date | null;
  auditFocus: AuditFocus;
};

/** @internal */
export const Audit$inboundSchema: z.ZodType<Audit, z.ZodTypeDef, unknown> = z
  .object({
    id: z.string(),
    customerOrganizationName: z.string(),
    customerDisplayName: z.nullable(z.string()),
    customerOrganizationId: z.string(),
    auditStartDate: z.string().datetime({ offset: true }).transform(v =>
      new Date(v)
    ),
    auditEndDate: z.string().datetime({ offset: true }).transform(v =>
      new Date(v)
    ),
    earlyAccessStartsAt: z.nullable(
      z.string().datetime({ offset: true }).transform(v => new Date(v)),
    ),
    framework: z.string(),
    allowAuditorEmails: z.array(z.string()),
    allowAllAuditors: z.boolean(),
    deletionDate: z.nullable(
      z.string().datetime({ offset: true }).transform(v => new Date(v)),
    ),
    creationDate: z.string().datetime({ offset: true }).transform(v =>
      new Date(v)
    ),
    modificationDate: z.nullable(
      z.string().datetime({ offset: true }).transform(v => new Date(v)),
    ),
    completionDate: z.nullable(
      z.string().datetime({ offset: true }).transform(v => new Date(v)),
    ),
    auditFocus: AuditFocus$inboundSchema,
  });

export function auditFromJSON(
  jsonString: string,
): SafeParseResult<Audit, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Audit$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Audit' from JSON`,
  );
}
