/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { ClosedEnum } from "../../types/enums.js";

export const AuditVendorStatus = {
  Active: "ACTIVE",
  Archived: "ARCHIVED",
  InProcurement: "IN_PROCUREMENT",
} as const;
export type AuditVendorStatus = ClosedEnum<typeof AuditVendorStatus>;

/** @internal */
export const AuditVendorStatus$inboundSchema: z.ZodNativeEnum<
  typeof AuditVendorStatus
> = z.nativeEnum(AuditVendorStatus);
/** @internal */
export const AuditVendorStatus$outboundSchema: z.ZodNativeEnum<
  typeof AuditVendorStatus
> = AuditVendorStatus$inboundSchema;
