/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { ClosedEnum } from "../../types/enums.js";

/**
 * CIA triad category returned by the auditor API.
 */
export const AuditRiskCia = {
  Availability: "AVAILABILITY",
  Confidentiality: "CONFIDENTIALITY",
  Integrity: "INTEGRITY",
} as const;
/**
 * CIA triad category returned by the auditor API.
 */
export type AuditRiskCia = ClosedEnum<typeof AuditRiskCia>;

/** @internal */
export const AuditRiskCia$inboundSchema: z.ZodNativeEnum<typeof AuditRiskCia> =
  z.nativeEnum(AuditRiskCia);
