/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { ClosedEnum } from "../../types/enums.js";

/**
 * An auditor's assessment of a control within an audit. This is the full flat
 *
 * @remarks
 * union of every framework's assessment states (the superset); a given audit's
 * framework only uses its own subset. `NOT_ASSESSED` is shared by all
 * frameworks and is the default for a control that has not yet been assessed.
 *
 * Which states apply to which framework:
 * - Most frameworks (e.g. SOC 2): `IN_PLACE`, `NOT_IN_PLACE`, `PARTIAL`, `NOT_ASSESSED`
 * - ISO 27001: `CONFORMING`, `MINOR_NON_CONFORMITY`, `MAJOR_NON_CONFORMITY`, `NOT_ASSESSED`
 * - FedRAMP: `SATISFIED`, `NOT_SATISFIED`, `OTHER_THAN_SATISFIED`, `NOT_ASSESSED`
 * - FedRAMP Key Security Indicators (KSI): `TRUE`, `FALSE`, `PARTIAL`, `NOT_ASSESSED`
 *
 * Distinct from `ControlStatus`, which is the computed tests/documents-passing
 * status — a different concept.
 */
export const AuditControlAssessmentState = {
  InPlace: "IN_PLACE",
  NotInPlace: "NOT_IN_PLACE",
  Partial: "PARTIAL",
  NotAssessed: "NOT_ASSESSED",
  Conforming: "CONFORMING",
  MinorNonConformity: "MINOR_NON_CONFORMITY",
  MajorNonConformity: "MAJOR_NON_CONFORMITY",
  Satisfied: "SATISFIED",
  NotSatisfied: "NOT_SATISFIED",
  OtherThanSatisfied: "OTHER_THAN_SATISFIED",
  True: "TRUE",
  False: "FALSE",
} as const;
/**
 * An auditor's assessment of a control within an audit. This is the full flat
 *
 * @remarks
 * union of every framework's assessment states (the superset); a given audit's
 * framework only uses its own subset. `NOT_ASSESSED` is shared by all
 * frameworks and is the default for a control that has not yet been assessed.
 *
 * Which states apply to which framework:
 * - Most frameworks (e.g. SOC 2): `IN_PLACE`, `NOT_IN_PLACE`, `PARTIAL`, `NOT_ASSESSED`
 * - ISO 27001: `CONFORMING`, `MINOR_NON_CONFORMITY`, `MAJOR_NON_CONFORMITY`, `NOT_ASSESSED`
 * - FedRAMP: `SATISFIED`, `NOT_SATISFIED`, `OTHER_THAN_SATISFIED`, `NOT_ASSESSED`
 * - FedRAMP Key Security Indicators (KSI): `TRUE`, `FALSE`, `PARTIAL`, `NOT_ASSESSED`
 *
 * Distinct from `ControlStatus`, which is the computed tests/documents-passing
 * status — a different concept.
 */
export type AuditControlAssessmentState = ClosedEnum<
  typeof AuditControlAssessmentState
>;

/** @internal */
export const AuditControlAssessmentState$inboundSchema: z.ZodNativeEnum<
  typeof AuditControlAssessmentState
> = z.nativeEnum(AuditControlAssessmentState);
