/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { ClosedEnum } from "../../types/enums.js";

export const AuditorEnabledStateTransition = {
  Accept: "ACCEPT",
  MarkApplicable: "MARK_APPLICABLE",
  Flag: "FLAG",
  MarkNa: "MARK_NA",
  ReadyForAudit: "READY_FOR_AUDIT",
} as const;
export type AuditorEnabledStateTransition = ClosedEnum<
  typeof AuditorEnabledStateTransition
>;

/** @internal */
export const AuditorEnabledStateTransition$inboundSchema: z.ZodNativeEnum<
  typeof AuditorEnabledStateTransition
> = z.nativeEnum(AuditorEnabledStateTransition);
/** @internal */
export const AuditorEnabledStateTransition$outboundSchema: z.ZodNativeEnum<
  typeof AuditorEnabledStateTransition
> = AuditorEnabledStateTransition$inboundSchema;
