/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import { ControlSource, ControlSource$inboundSchema } from "./controlsource.js";
import { CustomField, CustomField$inboundSchema } from "./customfield.js";
import { Section, Section$inboundSchema } from "./section.js";

/**
 * The control's owner.
 */
export type Owner = {
  /**
   * Unique identifier for the person.
   */
  id: string;
  /**
   * Name of the person that is shown in product.
   */
  displayName: string;
  /**
   * Email address of the person.
   */
  emailAddress: string;
};

export type AuditorControl = {
  /**
   * The control's unique ID.
   */
  id: string;
  /**
   * The control's external ID.
   */
  externalId: string | null;
  /**
   * The control's name.
   */
  name: string;
  /**
   * The control's description.
   */
  description: string;
  source: ControlSource;
  /**
   * The security domains that the control belongs to.
   */
  domains: Array<string>;
  /**
   * The control's owner.
   */
  owner: Owner | null;
  /**
   * The control's GDPR role, if the control is a GDPR control.
   */
  role?: string | null | undefined;
  /**
   * The control's custom field values, if control custom fields is included in your Vanta instance.
   */
  customFields: Array<CustomField>;
  /**
   * The report standard framework fulfilled by the control.
   */
  framework: string;
  /**
   * Sections of a framework that this control satisfies
   */
  sections: Array<Section>;
};

/** @internal */
export const Owner$inboundSchema: z.ZodType<Owner, z.ZodTypeDef, unknown> = z
  .object({
    id: z.string(),
    displayName: z.string(),
    emailAddress: z.string(),
  });

export function ownerFromJSON(
  jsonString: string,
): SafeParseResult<Owner, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Owner$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Owner' from JSON`,
  );
}

/** @internal */
export const AuditorControl$inboundSchema: z.ZodType<
  AuditorControl,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
  externalId: z.nullable(z.string()),
  name: z.string(),
  description: z.string(),
  source: ControlSource$inboundSchema,
  domains: z.array(z.string()),
  owner: z.nullable(z.lazy(() => Owner$inboundSchema)),
  role: z.nullable(z.string()).optional(),
  customFields: z.array(CustomField$inboundSchema),
  framework: z.string(),
  sections: z.array(Section$inboundSchema),
});

export function auditorControlFromJSON(
  jsonString: string,
): SafeParseResult<AuditorControl, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AuditorControl$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AuditorControl' from JSON`,
  );
}
