/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { ClosedEnum } from "../../types/enums.js";

export const AuditFocus = {
  External: "EXTERNAL",
  Internal: "INTERNAL",
} as const;
export type AuditFocus = ClosedEnum<typeof AuditFocus>;

/** @internal */
export const AuditFocus$inboundSchema: z.ZodNativeEnum<typeof AuditFocus> = z
  .nativeEnum(AuditFocus);
/** @internal */
export const AuditFocus$outboundSchema: z.ZodNativeEnum<typeof AuditFocus> =
  AuditFocus$inboundSchema;
