/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { ClosedEnum } from "../../types/enums.js";

export const AuditEvidenceType = {
  EvidenceRequest: "Evidence Request",
  Policy: "Policy",
  Test: "Test",
} as const;
export type AuditEvidenceType = ClosedEnum<typeof AuditEvidenceType>;

/** @internal */
export const AuditEvidenceType$inboundSchema: z.ZodNativeEnum<
  typeof AuditEvidenceType
> = z.nativeEnum(AuditEvidenceType);
/** @internal */
export const AuditEvidenceType$outboundSchema: z.ZodNativeEnum<
  typeof AuditEvidenceType
> = AuditEvidenceType$inboundSchema;
