/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { ClosedEnum } from "../../types/enums.js";

/**
 * The possible outcomes of a status check. The outcome can be one of the following:
 *
 * @remarks
 * FAIL:  The check is failing.
 * IN_PROGRESS: The check needs further data from the given computer in order to evaluate. The field(s) needed from a computer to calculate the ComputerStatusOutcome were null.
 * NA: The check is not applicable for the given computer.
 * PASS: The check is passing.
 */
export const ComputerStatusOutcome = {
  Fail: "FAIL",
  InProgress: "IN_PROGRESS",
  Na: "NA",
  Pass: "PASS",
} as const;
/**
 * The possible outcomes of a status check. The outcome can be one of the following:
 *
 * @remarks
 * FAIL:  The check is failing.
 * IN_PROGRESS: The check needs further data from the given computer in order to evaluate. The field(s) needed from a computer to calculate the ComputerStatusOutcome were null.
 * NA: The check is not applicable for the given computer.
 * PASS: The check is passing.
 */
export type ComputerStatusOutcome = ClosedEnum<typeof ComputerStatusOutcome>;

/** @internal */
export const ComputerStatusOutcome$inboundSchema: z.ZodNativeEnum<
  typeof ComputerStatusOutcome
> = z.nativeEnum(ComputerStatusOutcome);
