/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import { ControlSource, ControlSource$inboundSchema } from "./controlsource.js";
import { CustomField, CustomField$inboundSchema } from "./customfield.js";

/**
 * The control's owner.
 */
export type ControlOwner = {
  /**
   * Unique identifier for the person.
   */
  id: string;
  /**
   * Name of the person that is shown in product.
   */
  displayName: string;
  /**
   * Email address of the person.
   */
  emailAddress: string;
};

export type Control = {
  /**
   * The control's unique ID.
   */
  id: string;
  /**
   * The control's external ID.
   */
  externalId: string | null;
  /**
   * The control's name.
   */
  name: string;
  /**
   * The control's description.
   */
  description: string;
  source: ControlSource;
  /**
   * The security domains that the control belongs to.
   */
  domains: Array<string>;
  /**
   * The control's owner.
   */
  owner: ControlOwner | null;
  /**
   * The control's GDPR role, if the control is a GDPR control.
   */
  role?: string | null | undefined;
  /**
   * The control's custom field values, if control custom fields is included in your Vanta instance.
   */
  customFields: Array<CustomField>;
};

/** @internal */
export const ControlOwner$inboundSchema: z.ZodType<
  ControlOwner,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
  displayName: z.string(),
  emailAddress: z.string(),
});

export function controlOwnerFromJSON(
  jsonString: string,
): SafeParseResult<ControlOwner, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ControlOwner$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ControlOwner' from JSON`,
  );
}

/** @internal */
export const Control$inboundSchema: z.ZodType<Control, z.ZodTypeDef, unknown> =
  z.object({
    id: z.string(),
    externalId: z.nullable(z.string()),
    name: z.string(),
    description: z.string(),
    source: ControlSource$inboundSchema,
    domains: z.array(z.string()),
    owner: z.nullable(z.lazy(() => ControlOwner$inboundSchema)),
    role: z.nullable(z.string()).optional(),
    customFields: z.array(CustomField$inboundSchema),
  });

export function controlFromJSON(
  jsonString: string,
): SafeParseResult<Control, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Control$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Control' from JSON`,
  );
}
