/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * A custom task.
 */
export type CustomTask = {
  name: string;
};

/** @internal */
export const CustomTask$inboundSchema: z.ZodType<
  CustomTask,
  z.ZodTypeDef,
  unknown
> = z.object({
  name: z.string(),
});

export function customTaskFromJSON(
  jsonString: string,
): SafeParseResult<CustomTask, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CustomTask$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CustomTask' from JSON`,
  );
}
