/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

/**
 * Deletes an existing comment on a control.
 *
 * @remarks
 * Only the original author of the comment can delete it.
 */
export type DeleteAuditControlCommentInput = {
  /**
   * Email address of the comment author.
   *
   * @remarks
   * Must match an existing Vanta user who belongs to the audit firm making the API request.
   * This email uniquely identifies the author across systems.
   */
  email: string;
};

/** @internal */
export type DeleteAuditControlCommentInput$Outbound = {
  email: string;
};

/** @internal */
export const DeleteAuditControlCommentInput$outboundSchema: z.ZodType<
  DeleteAuditControlCommentInput$Outbound,
  z.ZodTypeDef,
  DeleteAuditControlCommentInput
> = z.object({
  email: z.string(),
});

export function deleteAuditControlCommentInputToJSON(
  deleteAuditControlCommentInput: DeleteAuditControlCommentInput,
): string {
  return JSON.stringify(
    DeleteAuditControlCommentInput$outboundSchema.parse(
      deleteAuditControlCommentInput,
    ),
  );
}
