/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

/**
 * Deletes an existing comment on an information request.
 *
 * @remarks
 * Only the original author of the comment can delete it.
 */
export type DeleteInformationRequestCommentInput = {
  /**
   * Email address of the comment author.
   *
   * @remarks
   * Must match an existing Vanta user who belongs to the audit firm making the API request.
   * This email uniquely identifies the author across systems.
   */
  email: string;
};

/** @internal */
export type DeleteInformationRequestCommentInput$Outbound = {
  email: string;
};

/** @internal */
export const DeleteInformationRequestCommentInput$outboundSchema: z.ZodType<
  DeleteInformationRequestCommentInput$Outbound,
  z.ZodTypeDef,
  DeleteInformationRequestCommentInput
> = z.object({
  email: z.string(),
});

export function deleteInformationRequestCommentInputToJSON(
  deleteInformationRequestCommentInput: DeleteInformationRequestCommentInput,
): string {
  return JSON.stringify(
    DeleteInformationRequestCommentInput$outboundSchema.parse(
      deleteInformationRequestCommentInput,
    ),
  );
}
