/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { ClosedEnum } from "../../types/enums.js";

/**
 * ExternalFindingSeverity describes the severity of an external finding (Vulnerability or Security Alert)
 */
export const ExternalFindingSeverity = {
  Critical: "CRITICAL",
  High: "HIGH",
  Low: "LOW",
  Medium: "MEDIUM",
} as const;
/**
 * ExternalFindingSeverity describes the severity of an external finding (Vulnerability or Security Alert)
 */
export type ExternalFindingSeverity = ClosedEnum<
  typeof ExternalFindingSeverity
>;

/** @internal */
export const ExternalFindingSeverity$outboundSchema: z.ZodNativeEnum<
  typeof ExternalFindingSeverity
> = z.nativeEnum(ExternalFindingSeverity);
