/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

/**
 * Input for flagging evidence on an information request, indicating issues
 *
 * @remarks
 * that need to be addressed. This changes the request's approvalStatus to
 * a flagged state and creates an activity log entry.
 *
 * The customer will be notified and can resubmit evidence after addressing the issues.
 */
export type FlagInformationRequestEvidenceInput = {
  /**
   * Email of the auditor flagging the evidence.
   *
   * @remarks
   * Must match an existing Vanta user who belongs to the audit firm making the API request.
   */
  auditorEmail: string;
  /**
   * Detailed explanation of what issues were found with the evidence.
   *
   * @remarks
   * This reason is visible to the customer and guides them on what to fix.
   * Must be at least 1 character.
   */
  reason: string;
};

/** @internal */
export type FlagInformationRequestEvidenceInput$Outbound = {
  auditorEmail: string;
  reason: string;
};

/** @internal */
export const FlagInformationRequestEvidenceInput$outboundSchema: z.ZodType<
  FlagInformationRequestEvidenceInput$Outbound,
  z.ZodTypeDef,
  FlagInformationRequestEvidenceInput
> = z.object({
  auditorEmail: z.string(),
  reason: z.string(),
});

export function flagInformationRequestEvidenceInputToJSON(
  flagInformationRequestEvidenceInput: FlagInformationRequestEvidenceInput,
): string {
  return JSON.stringify(
    FlagInformationRequestEvidenceInput$outboundSchema.parse(
      flagInformationRequestEvidenceInput,
    ),
  );
}
