/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type FrameworkCodesByFramework = {
  /**
   * Display name of the in-scope framework these codes belong to.
   */
  framework: string;
  /**
   * Valid codes for this framework, sorted.
   */
  codes: Array<string>;
};

/** @internal */
export const FrameworkCodesByFramework$inboundSchema: z.ZodType<
  FrameworkCodesByFramework,
  z.ZodTypeDef,
  unknown
> = z.object({
  framework: z.string(),
  codes: z.array(z.string()),
});

export function frameworkCodesByFrameworkFromJSON(
  jsonString: string,
): SafeParseResult<FrameworkCodesByFramework, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => FrameworkCodesByFramework$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'FrameworkCodesByFramework' from JSON`,
  );
}
