/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * Framework codes response resource
 */
export type FrameworkCodes = {
  /**
   * Array of valid framework codes for the audit's framework (e.g., "CC6.1", "CC6.2").
   *
   * @remarks
   * These represent the different framework sections available for creating information requests.
   */
  frameworkCodes: Array<string>;
};

/** @internal */
export const FrameworkCodes$inboundSchema: z.ZodType<
  FrameworkCodes,
  z.ZodTypeDef,
  unknown
> = z.object({
  frameworkCodes: z.array(z.string()),
});

export function frameworkCodesFromJSON(
  jsonString: string,
): SafeParseResult<FrameworkCodes, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => FrameworkCodes$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'FrameworkCodes' from JSON`,
  );
}
