/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import { LinkEvidence, LinkEvidence$inboundSchema } from "./linkevidence.js";
import {
  ObservationEvidence,
  ObservationEvidence$inboundSchema,
} from "./observationevidence.js";
import {
  UploadedDocumentEvidence,
  UploadedDocumentEvidence$inboundSchema,
} from "./uploadeddocumentevidence.js";
import {
  VantaDocumentEvidence,
  VantaDocumentEvidence$inboundSchema,
} from "./vantadocumentevidence.js";
import {
  VantaPolicyEvidence,
  VantaPolicyEvidence$inboundSchema,
} from "./vantapolicyevidence.js";
import {
  VantaTestEvidence,
  VantaTestEvidence$inboundSchema,
} from "./vantatestevidence.js";
import {
  VantaTestSnapshotEvidence,
  VantaTestSnapshotEvidence$inboundSchema,
} from "./vantatestsnapshotevidence.js";

/**
 * Union type representing the different forms of evidence content.
 *
 * @remarks
 * The specific type is determined by the `evidenceType` field in InformationRequestEvidence.
 */
export type InformationRequestEvidenceUnion =
  | VantaTestEvidence
  | VantaTestSnapshotEvidence
  | VantaPolicyEvidence
  | UploadedDocumentEvidence
  | VantaDocumentEvidence
  | LinkEvidence
  | ObservationEvidence;

/** @internal */
export const InformationRequestEvidenceUnion$inboundSchema: z.ZodType<
  InformationRequestEvidenceUnion,
  z.ZodTypeDef,
  unknown
> = z.union([
  VantaTestEvidence$inboundSchema,
  VantaTestSnapshotEvidence$inboundSchema,
  VantaPolicyEvidence$inboundSchema,
  UploadedDocumentEvidence$inboundSchema,
  VantaDocumentEvidence$inboundSchema,
  LinkEvidence$inboundSchema,
  ObservationEvidence$inboundSchema,
]);

export function informationRequestEvidenceUnionFromJSON(
  jsonString: string,
): SafeParseResult<InformationRequestEvidenceUnion, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => InformationRequestEvidenceUnion$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'InformationRequestEvidenceUnion' from JSON`,
  );
}
