/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { ClosedEnum } from "../../types/enums.js";

export const InformationRequestSupportedEvidenceType = {
  UploadedDocument: "UPLOADED_DOCUMENT",
  Observation: "OBSERVATION",
  Link: "LINK",
  VantaDocument: "VANTA_DOCUMENT",
  VantaPolicy: "VANTA_POLICY",
  VantaTest: "VANTA_TEST",
  VantaTestSnapshot: "VANTA_TEST_SNAPSHOT",
} as const;
export type InformationRequestSupportedEvidenceType = ClosedEnum<
  typeof InformationRequestSupportedEvidenceType
>;

/** @internal */
export const InformationRequestSupportedEvidenceType$inboundSchema:
  z.ZodNativeEnum<typeof InformationRequestSupportedEvidenceType> = z
    .nativeEnum(InformationRequestSupportedEvidenceType);
/** @internal */
export const InformationRequestSupportedEvidenceType$outboundSchema:
  z.ZodNativeEnum<typeof InformationRequestSupportedEvidenceType> =
    InformationRequestSupportedEvidenceType$inboundSchema;
