/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { ClosedEnum } from "../../types/enums.js";

export const InformationRequestActivityType = {
  ChangeStatus: "CHANGE_STATUS",
  EditRequest: "EDIT_REQUEST",
  RemoveEvidence: "REMOVE_EVIDENCE",
  ShareEvidenceWithAuditor: "SHARE_EVIDENCE_WITH_AUDITOR",
  UploadEvidence: "UPLOAD_EVIDENCE",
} as const;
export type InformationRequestActivityType = ClosedEnum<
  typeof InformationRequestActivityType
>;

/** @internal */
export const InformationRequestActivityType$inboundSchema: z.ZodNativeEnum<
  typeof InformationRequestActivityType
> = z.nativeEnum(InformationRequestActivityType);
