/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { ClosedEnum } from "../../types/enums.js";

/**
 * Frequency cadence for the information request, indicating how often it recurs.
 */
export const InformationRequestCadence = {
  Annually: "ANNUALLY",
  Biannually: "BIANNUALLY",
  Monthly: "MONTHLY",
  Quarterly: "QUARTERLY",
} as const;
/**
 * Frequency cadence for the information request, indicating how often it recurs.
 */
export type InformationRequestCadence = ClosedEnum<
  typeof InformationRequestCadence
>;

/** @internal */
export const InformationRequestCadence$outboundSchema: z.ZodNativeEnum<
  typeof InformationRequestCadence
> = z.nativeEnum(InformationRequestCadence);
