/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { ClosedEnum } from "../../types/enums.js";

/**
 * Current approval status of the information request, tracking its lifecycle through the audit process.
 *
 * @remarks
 *
 * The status progresses through the workflow: initial state → awaiting review → approved or flagged.
 * Status can move between awaiting review and flagged states as evidence is reviewed and resubmitted.
 */
export const InformationRequestApprovalStatus = {
  NeedsEvidence: "NEEDS_EVIDENCE",
  ReadyForAudit: "READY_FOR_AUDIT",
  AuditorApproved: "AUDITOR_APPROVED",
  AuditorFlagged: "AUDITOR_FLAGGED",
} as const;
/**
 * Current approval status of the information request, tracking its lifecycle through the audit process.
 *
 * @remarks
 *
 * The status progresses through the workflow: initial state → awaiting review → approved or flagged.
 * Status can move between awaiting review and flagged states as evidence is reviewed and resubmitted.
 */
export type InformationRequestApprovalStatus = ClosedEnum<
  typeof InformationRequestApprovalStatus
>;

/** @internal */
export const InformationRequestApprovalStatus$inboundSchema: z.ZodNativeEnum<
  typeof InformationRequestApprovalStatus
> = z.nativeEnum(InformationRequestApprovalStatus);
