/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { ClosedEnum } from "../../types/enums.js";

/**
 * Type of information request, defining what scope of evidence is needed.
 *
 * @remarks
 *
 * - POINT_IN_TIME: Evidence for a specific moment (e.g., current state of a policy)
 * - POPULATION: Evidence covering all items in a category (e.g., all employees)
 * - SAMPLE: Evidence for a representative sample (e.g., 10 random customer records)
 */
export const InformationRequestType = {
  PointInTime: "POINT_IN_TIME",
  Population: "POPULATION",
  Sample: "SAMPLE",
} as const;
/**
 * Type of information request, defining what scope of evidence is needed.
 *
 * @remarks
 *
 * - POINT_IN_TIME: Evidence for a specific moment (e.g., current state of a policy)
 * - POPULATION: Evidence covering all items in a category (e.g., all employees)
 * - SAMPLE: Evidence for a representative sample (e.g., 10 random customer records)
 */
export type InformationRequestType = ClosedEnum<typeof InformationRequestType>;

/** @internal */
export const InformationRequestType$inboundSchema: z.ZodNativeEnum<
  typeof InformationRequestType
> = z.nativeEnum(InformationRequestType);
/** @internal */
export const InformationRequestType$outboundSchema: z.ZodNativeEnum<
  typeof InformationRequestType
> = InformationRequestType$inboundSchema;
