/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import { TaskStatus, TaskStatus$inboundSchema } from "./taskstatus.js";
import {
  TaskTypeINSTALLDEVICEMONITORING,
  TaskTypeINSTALLDEVICEMONITORING$inboundSchema,
} from "./tasktypeinstalldevicemonitoring.js";

/**
 * If the task is disabled, the reason and date when it was disabled.
 */
export type InstallDeviceMonitoringTaskSummaryDisabled = {
  date: Date;
  reason: string | null;
};

/**
 * Task summary for installing device monitoring.
 */
export type InstallDeviceMonitoringTaskSummary = {
  taskType: TaskTypeINSTALLDEVICEMONITORING;
  /**
   * The status of a task.
   *
   * @remarks
   * - COMPLETE: The task has been completed.
   * - DUE_SOON: The task is due soon.
   * - OVERDUE: The task is overdue.
   * - NONE: The task is not assigned.
   */
  status: TaskStatus;
  /**
   * The due date of the task.
   */
  dueDate: Date | null;
  /**
   * The date the task was completed.
   */
  completionDate: Date | null;
  /**
   * If the task is disabled, the reason and date when it was disabled.
   */
  disabled: InstallDeviceMonitoringTaskSummaryDisabled | null;
};

/** @internal */
export const InstallDeviceMonitoringTaskSummaryDisabled$inboundSchema:
  z.ZodType<InstallDeviceMonitoringTaskSummaryDisabled, z.ZodTypeDef, unknown> =
    z.object({
      date: z.string().datetime({ offset: true }).transform(v => new Date(v)),
      reason: z.nullable(z.string()),
    });

export function installDeviceMonitoringTaskSummaryDisabledFromJSON(
  jsonString: string,
): SafeParseResult<
  InstallDeviceMonitoringTaskSummaryDisabled,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      InstallDeviceMonitoringTaskSummaryDisabled$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'InstallDeviceMonitoringTaskSummaryDisabled' from JSON`,
  );
}

/** @internal */
export const InstallDeviceMonitoringTaskSummary$inboundSchema: z.ZodType<
  InstallDeviceMonitoringTaskSummary,
  z.ZodTypeDef,
  unknown
> = z.object({
  taskType: TaskTypeINSTALLDEVICEMONITORING$inboundSchema,
  status: TaskStatus$inboundSchema,
  dueDate: z.nullable(
    z.string().datetime({ offset: true }).transform(v => new Date(v)),
  ),
  completionDate: z.nullable(
    z.string().datetime({ offset: true }).transform(v => new Date(v)),
  ),
  disabled: z.nullable(
    z.lazy(() => InstallDeviceMonitoringTaskSummaryDisabled$inboundSchema),
  ),
});

export function installDeviceMonitoringTaskSummaryFromJSON(
  jsonString: string,
): SafeParseResult<InstallDeviceMonitoringTaskSummary, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      InstallDeviceMonitoringTaskSummary$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'InstallDeviceMonitoringTaskSummary' from JSON`,
  );
}
