/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { ClosedEnum } from "../../types/enums.js";

export const IssueStatusTypeForSnapshot = {
  InProgress: "IN_PROGRESS",
  NotStarted: "NOT_STARTED",
  Closed: "CLOSED",
} as const;
export type IssueStatusTypeForSnapshot = ClosedEnum<
  typeof IssueStatusTypeForSnapshot
>;

/** @internal */
export const IssueStatusTypeForSnapshot$inboundSchema: z.ZodNativeEnum<
  typeof IssueStatusTypeForSnapshot
> = z.nativeEnum(IssueStatusTypeForSnapshot);
