/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { ClosedEnum } from "../../types/enums.js";

/**
 * Allowed values for the `orderBy` query parameter on issue snapshot item endpoints.
 */
export const IssueSnapshotItemOrderBy = {
  CreatedAt: "createdAt",
  LastModifiedAt: "lastModifiedAt",
  DetectedAt: "detectedAt",
} as const;
/**
 * Allowed values for the `orderBy` query parameter on issue snapshot item endpoints.
 */
export type IssueSnapshotItemOrderBy = ClosedEnum<
  typeof IssueSnapshotItemOrderBy
>;

/** @internal */
export const IssueSnapshotItemOrderBy$outboundSchema: z.ZodNativeEnum<
  typeof IssueSnapshotItemOrderBy
> = z.nativeEnum(IssueSnapshotItemOrderBy);
