/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type KeyValuePair = {
  /**
   * Key of key-value pair.
   */
  key: string;
  /**
   * Value of key-value pair.
   */
  value: string;
};

/** @internal */
export const KeyValuePair$inboundSchema: z.ZodType<
  KeyValuePair,
  z.ZodTypeDef,
  unknown
> = z.object({
  key: z.string(),
  value: z.string(),
});

export function keyValuePairFromJSON(
  jsonString: string,
): SafeParseResult<KeyValuePair, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => KeyValuePair$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'KeyValuePair' from JSON`,
  );
}
