/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * Evidence in the form of a link to external documentation or resources.
 */
export type LinkEvidence = {
  /**
   * The title or descriptive name for the link.
   */
  title: string;
  /**
   * Optional description providing additional context about the link.
   */
  description?: string | undefined;
  /**
   * The URL pointing to the external documentation or resource.
   */
  url: string;
};

/** @internal */
export const LinkEvidence$inboundSchema: z.ZodType<
  LinkEvidence,
  z.ZodTypeDef,
  unknown
> = z.object({
  title: z.string(),
  description: z.string().optional(),
  url: z.string(),
});

export function linkEvidenceFromJSON(
  jsonString: string,
): SafeParseResult<LinkEvidence, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => LinkEvidence$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'LinkEvidence' from JSON`,
  );
}
