/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * Evidence in the form of a text observation or note.
 */
export type ObservationEvidence = {
  /**
   * The text content of the observation.
   */
  observationDetails: string;
};

/** @internal */
export const ObservationEvidence$inboundSchema: z.ZodType<
  ObservationEvidence,
  z.ZodTypeDef,
  unknown
> = z.object({
  observationDetails: z.string(),
});

export function observationEvidenceFromJSON(
  jsonString: string,
): SafeParseResult<ObservationEvidence, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ObservationEvidence$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ObservationEvidence' from JSON`,
  );
}
