/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { ClosedEnum } from "../../types/enums.js";

/**
 * The possible types of the operating system. One of `mac_OS`, `linux`, or `windows`.
 */
export const OperatingSystemType = {
  MacOS: "macOS",
  Linux: "linux",
  Windows: "windows",
} as const;
/**
 * The possible types of the operating system. One of `mac_OS`, `linux`, or `windows`.
 */
export type OperatingSystemType = ClosedEnum<typeof OperatingSystemType>;

/** @internal */
export const OperatingSystemType$inboundSchema: z.ZodNativeEnum<
  typeof OperatingSystemType
> = z.nativeEnum(OperatingSystemType);
