/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { ClosedEnum } from "../../types/enums.js";

/**
 * Sort direction shared across the external REST API surface.
 *
 * @remarks
 *
 * `"asc"` for ascending, `"desc"` for descending. Endpoints expose this as the
 * `orderDirection` / `sortDirection` query parameter and map it onto whatever
 * internal direction representation the underlying service expects.
 */
export const OrderDirection = {
  Asc: "asc",
  Desc: "desc",
} as const;
/**
 * Sort direction shared across the external REST API surface.
 *
 * @remarks
 *
 * `"asc"` for ascending, `"desc"` for descending. Endpoints expose this as the
 * `orderDirection` / `sortDirection` query parameter and map it onto whatever
 * internal direction representation the underlying service expects.
 */
export type OrderDirection = ClosedEnum<typeof OrderDirection>;

/** @internal */
export const OrderDirection$outboundSchema: z.ZodNativeEnum<
  typeof OrderDirection
> = z.nativeEnum(OrderDirection);
