/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import { PageInfo, PageInfo$inboundSchema } from "./pageinfo.js";
import { RiskSnapshot, RiskSnapshot$inboundSchema } from "./risksnapshot.js";

export type PaginatedResponseRiskSnapshotResults = {
  data: Array<RiskSnapshot>;
  /**
   * Provides information about the pagination of a dataset.
   */
  pageInfo: PageInfo;
};

export type PaginatedResponseRiskSnapshot = {
  results: PaginatedResponseRiskSnapshotResults;
};

/** @internal */
export const PaginatedResponseRiskSnapshotResults$inboundSchema: z.ZodType<
  PaginatedResponseRiskSnapshotResults,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: z.array(RiskSnapshot$inboundSchema),
  pageInfo: PageInfo$inboundSchema,
});

export function paginatedResponseRiskSnapshotResultsFromJSON(
  jsonString: string,
): SafeParseResult<PaginatedResponseRiskSnapshotResults, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      PaginatedResponseRiskSnapshotResults$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PaginatedResponseRiskSnapshotResults' from JSON`,
  );
}

/** @internal */
export const PaginatedResponseRiskSnapshot$inboundSchema: z.ZodType<
  PaginatedResponseRiskSnapshot,
  z.ZodTypeDef,
  unknown
> = z.object({
  results: z.lazy(() => PaginatedResponseRiskSnapshotResults$inboundSchema),
});

export function paginatedResponseRiskSnapshotFromJSON(
  jsonString: string,
): SafeParseResult<PaginatedResponseRiskSnapshot, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PaginatedResponseRiskSnapshot$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PaginatedResponseRiskSnapshot' from JSON`,
  );
}
