/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  AuditIntegration,
  AuditIntegration$inboundSchema,
} from "./auditintegration.js";
import { PageInfo, PageInfo$inboundSchema } from "./pageinfo.js";

export type PaginatedResponseAuditIntegrationResults = {
  data: Array<AuditIntegration>;
  /**
   * Provides information about the pagination of a dataset.
   */
  pageInfo: PageInfo;
};

export type PaginatedResponseAuditIntegration = {
  results: PaginatedResponseAuditIntegrationResults;
};

/** @internal */
export const PaginatedResponseAuditIntegrationResults$inboundSchema: z.ZodType<
  PaginatedResponseAuditIntegrationResults,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: z.array(AuditIntegration$inboundSchema),
  pageInfo: PageInfo$inboundSchema,
});

export function paginatedResponseAuditIntegrationResultsFromJSON(
  jsonString: string,
): SafeParseResult<
  PaginatedResponseAuditIntegrationResults,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      PaginatedResponseAuditIntegrationResults$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'PaginatedResponseAuditIntegrationResults' from JSON`,
  );
}

/** @internal */
export const PaginatedResponseAuditIntegration$inboundSchema: z.ZodType<
  PaginatedResponseAuditIntegration,
  z.ZodTypeDef,
  unknown
> = z.object({
  results: z.lazy(() => PaginatedResponseAuditIntegrationResults$inboundSchema),
});

export function paginatedResponseAuditIntegrationFromJSON(
  jsonString: string,
): SafeParseResult<PaginatedResponseAuditIntegration, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PaginatedResponseAuditIntegration$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PaginatedResponseAuditIntegration' from JSON`,
  );
}
