/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  IssueSnapshotItem,
  IssueSnapshotItem$inboundSchema,
} from "./issuesnapshotitem.js";
import { PageInfo, PageInfo$inboundSchema } from "./pageinfo.js";

export type PaginatedIssueSnapshotItemsResponseResults = {
  data: Array<IssueSnapshotItem>;
  /**
   * Provides information about the pagination of a dataset.
   */
  pageInfo: PageInfo;
};

export type PaginatedIssueSnapshotItemsResponse = {
  results: PaginatedIssueSnapshotItemsResponseResults;
};

/** @internal */
export const PaginatedIssueSnapshotItemsResponseResults$inboundSchema:
  z.ZodType<PaginatedIssueSnapshotItemsResponseResults, z.ZodTypeDef, unknown> =
    z.object({
      data: z.array(IssueSnapshotItem$inboundSchema),
      pageInfo: PageInfo$inboundSchema,
    });

export function paginatedIssueSnapshotItemsResponseResultsFromJSON(
  jsonString: string,
): SafeParseResult<
  PaginatedIssueSnapshotItemsResponseResults,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      PaginatedIssueSnapshotItemsResponseResults$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'PaginatedIssueSnapshotItemsResponseResults' from JSON`,
  );
}

/** @internal */
export const PaginatedIssueSnapshotItemsResponse$inboundSchema: z.ZodType<
  PaginatedIssueSnapshotItemsResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  results: z.lazy(() =>
    PaginatedIssueSnapshotItemsResponseResults$inboundSchema
  ),
});

export function paginatedIssueSnapshotItemsResponseFromJSON(
  jsonString: string,
): SafeParseResult<PaginatedIssueSnapshotItemsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      PaginatedIssueSnapshotItemsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PaginatedIssueSnapshotItemsResponse' from JSON`,
  );
}
