/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import { Audit, Audit$inboundSchema } from "./audit.js";
import { PageInfo, PageInfo$inboundSchema } from "./pageinfo.js";

export type Results = {
  data: Array<Audit>;
  /**
   * Provides information about the pagination of a dataset.
   */
  pageInfo: PageInfo;
};

export type PaginatedResponseAudit = {
  results: Results;
};

/** @internal */
export const Results$inboundSchema: z.ZodType<Results, z.ZodTypeDef, unknown> =
  z.object({
    data: z.array(Audit$inboundSchema),
    pageInfo: PageInfo$inboundSchema,
  });

export function resultsFromJSON(
  jsonString: string,
): SafeParseResult<Results, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Results$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Results' from JSON`,
  );
}

/** @internal */
export const PaginatedResponseAudit$inboundSchema: z.ZodType<
  PaginatedResponseAudit,
  z.ZodTypeDef,
  unknown
> = z.object({
  results: z.lazy(() => Results$inboundSchema),
});

export function paginatedResponseAuditFromJSON(
  jsonString: string,
): SafeParseResult<PaginatedResponseAudit, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PaginatedResponseAudit$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PaginatedResponseAudit' from JSON`,
  );
}
