/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import { AuditVendor, AuditVendor$inboundSchema } from "./auditvendor.js";
import { PageInfo, PageInfo$inboundSchema } from "./pageinfo.js";

export type PaginatedResponseAuditVendorResults = {
  data: Array<AuditVendor>;
  /**
   * Provides information about the pagination of a dataset.
   */
  pageInfo: PageInfo;
};

export type PaginatedResponseAuditVendor = {
  results: PaginatedResponseAuditVendorResults;
};

/** @internal */
export const PaginatedResponseAuditVendorResults$inboundSchema: z.ZodType<
  PaginatedResponseAuditVendorResults,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: z.array(AuditVendor$inboundSchema),
  pageInfo: PageInfo$inboundSchema,
});

export function paginatedResponseAuditVendorResultsFromJSON(
  jsonString: string,
): SafeParseResult<PaginatedResponseAuditVendorResults, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      PaginatedResponseAuditVendorResults$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PaginatedResponseAuditVendorResults' from JSON`,
  );
}

/** @internal */
export const PaginatedResponseAuditVendor$inboundSchema: z.ZodType<
  PaginatedResponseAuditVendor,
  z.ZodTypeDef,
  unknown
> = z.object({
  results: z.lazy(() => PaginatedResponseAuditVendorResults$inboundSchema),
});

export function paginatedResponseAuditVendorFromJSON(
  jsonString: string,
): SafeParseResult<PaginatedResponseAuditVendor, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PaginatedResponseAuditVendor$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PaginatedResponseAuditVendor' from JSON`,
  );
}
