/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  MonitoredComputer,
  MonitoredComputer$inboundSchema,
} from "./monitoredcomputer.js";
import { PageInfo, PageInfo$inboundSchema } from "./pageinfo.js";

export type PaginatedResponseMonitoredComputerResults = {
  data: Array<MonitoredComputer>;
  /**
   * Provides information about the pagination of a dataset.
   */
  pageInfo: PageInfo;
};

export type PaginatedResponseMonitoredComputer = {
  results: PaginatedResponseMonitoredComputerResults;
};

/** @internal */
export const PaginatedResponseMonitoredComputerResults$inboundSchema: z.ZodType<
  PaginatedResponseMonitoredComputerResults,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: z.array(MonitoredComputer$inboundSchema),
  pageInfo: PageInfo$inboundSchema,
});

export function paginatedResponseMonitoredComputerResultsFromJSON(
  jsonString: string,
): SafeParseResult<
  PaginatedResponseMonitoredComputerResults,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      PaginatedResponseMonitoredComputerResults$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'PaginatedResponseMonitoredComputerResults' from JSON`,
  );
}

/** @internal */
export const PaginatedResponseMonitoredComputer$inboundSchema: z.ZodType<
  PaginatedResponseMonitoredComputer,
  z.ZodTypeDef,
  unknown
> = z.object({
  results: z.lazy(() =>
    PaginatedResponseMonitoredComputerResults$inboundSchema
  ),
});

export function paginatedResponseMonitoredComputerFromJSON(
  jsonString: string,
): SafeParseResult<PaginatedResponseMonitoredComputer, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      PaginatedResponseMonitoredComputer$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PaginatedResponseMonitoredComputer' from JSON`,
  );
}
