/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import { CodeChange, CodeChange$inboundSchema } from "./codechange.js";
import { PageInfo, PageInfo$inboundSchema } from "./pageinfo.js";

export type PaginatedResponseCodeChangeResults = {
  data: Array<CodeChange>;
  /**
   * Provides information about the pagination of a dataset.
   */
  pageInfo: PageInfo;
};

export type PaginatedResponseCodeChange = {
  results: PaginatedResponseCodeChangeResults;
};

/** @internal */
export const PaginatedResponseCodeChangeResults$inboundSchema: z.ZodType<
  PaginatedResponseCodeChangeResults,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: z.array(CodeChange$inboundSchema),
  pageInfo: PageInfo$inboundSchema,
});

export function paginatedResponseCodeChangeResultsFromJSON(
  jsonString: string,
): SafeParseResult<PaginatedResponseCodeChangeResults, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      PaginatedResponseCodeChangeResults$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PaginatedResponseCodeChangeResults' from JSON`,
  );
}

/** @internal */
export const PaginatedResponseCodeChange$inboundSchema: z.ZodType<
  PaginatedResponseCodeChange,
  z.ZodTypeDef,
  unknown
> = z.object({
  results: z.lazy(() => PaginatedResponseCodeChangeResults$inboundSchema),
});

export function paginatedResponseCodeChangeFromJSON(
  jsonString: string,
): SafeParseResult<PaginatedResponseCodeChange, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PaginatedResponseCodeChange$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PaginatedResponseCodeChange' from JSON`,
  );
}
