/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import { AccountAccess, AccountAccess$inboundSchema } from "./accountaccess.js";
import { PageInfo, PageInfo$inboundSchema } from "./pageinfo.js";

export type PaginatedResponseAccountAccessResults = {
  data: Array<AccountAccess>;
  /**
   * Provides information about the pagination of a dataset.
   */
  pageInfo: PageInfo;
};

export type PaginatedResponseAccountAccess = {
  results: PaginatedResponseAccountAccessResults;
};

/** @internal */
export const PaginatedResponseAccountAccessResults$inboundSchema: z.ZodType<
  PaginatedResponseAccountAccessResults,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: z.array(AccountAccess$inboundSchema),
  pageInfo: PageInfo$inboundSchema,
});

export function paginatedResponseAccountAccessResultsFromJSON(
  jsonString: string,
): SafeParseResult<PaginatedResponseAccountAccessResults, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      PaginatedResponseAccountAccessResults$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PaginatedResponseAccountAccessResults' from JSON`,
  );
}

/** @internal */
export const PaginatedResponseAccountAccess$inboundSchema: z.ZodType<
  PaginatedResponseAccountAccess,
  z.ZodTypeDef,
  unknown
> = z.object({
  results: z.lazy(() => PaginatedResponseAccountAccessResults$inboundSchema),
});

export function paginatedResponseAccountAccessFromJSON(
  jsonString: string,
): SafeParseResult<PaginatedResponseAccountAccess, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PaginatedResponseAccountAccess$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PaginatedResponseAccountAccess' from JSON`,
  );
}
