/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import { PageInfo, PageInfo$inboundSchema } from "./pageinfo.js";
import {
  VulnerableAsset,
  VulnerableAsset$inboundSchema,
} from "./vulnerableasset.js";

export type PaginatedResponseVulnerableAssetResults = {
  data: Array<VulnerableAsset>;
  /**
   * Provides information about the pagination of a dataset.
   */
  pageInfo: PageInfo;
};

export type PaginatedResponseVulnerableAsset = {
  results: PaginatedResponseVulnerableAssetResults;
};

/** @internal */
export const PaginatedResponseVulnerableAssetResults$inboundSchema: z.ZodType<
  PaginatedResponseVulnerableAssetResults,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: z.array(VulnerableAsset$inboundSchema),
  pageInfo: PageInfo$inboundSchema,
});

export function paginatedResponseVulnerableAssetResultsFromJSON(
  jsonString: string,
): SafeParseResult<
  PaginatedResponseVulnerableAssetResults,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      PaginatedResponseVulnerableAssetResults$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'PaginatedResponseVulnerableAssetResults' from JSON`,
  );
}

/** @internal */
export const PaginatedResponseVulnerableAsset$inboundSchema: z.ZodType<
  PaginatedResponseVulnerableAsset,
  z.ZodTypeDef,
  unknown
> = z.object({
  results: z.lazy(() => PaginatedResponseVulnerableAssetResults$inboundSchema),
});

export function paginatedResponseVulnerableAssetFromJSON(
  jsonString: string,
): SafeParseResult<PaginatedResponseVulnerableAsset, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PaginatedResponseVulnerableAsset$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PaginatedResponseVulnerableAsset' from JSON`,
  );
}
