/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  AuditControlComment,
  AuditControlComment$inboundSchema,
} from "./auditcontrolcomment.js";
import { PageInfo, PageInfo$inboundSchema } from "./pageinfo.js";

export type PaginatedResponseAuditControlCommentResults = {
  data: Array<AuditControlComment>;
  /**
   * Provides information about the pagination of a dataset.
   */
  pageInfo: PageInfo;
};

export type PaginatedResponseAuditControlComment = {
  results: PaginatedResponseAuditControlCommentResults;
};

/** @internal */
export const PaginatedResponseAuditControlCommentResults$inboundSchema:
  z.ZodType<
    PaginatedResponseAuditControlCommentResults,
    z.ZodTypeDef,
    unknown
  > = z.object({
    data: z.array(AuditControlComment$inboundSchema),
    pageInfo: PageInfo$inboundSchema,
  });

export function paginatedResponseAuditControlCommentResultsFromJSON(
  jsonString: string,
): SafeParseResult<
  PaginatedResponseAuditControlCommentResults,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      PaginatedResponseAuditControlCommentResults$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'PaginatedResponseAuditControlCommentResults' from JSON`,
  );
}

/** @internal */
export const PaginatedResponseAuditControlComment$inboundSchema: z.ZodType<
  PaginatedResponseAuditControlComment,
  z.ZodTypeDef,
  unknown
> = z.object({
  results: z.lazy(() =>
    PaginatedResponseAuditControlCommentResults$inboundSchema
  ),
});

export function paginatedResponseAuditControlCommentFromJSON(
  jsonString: string,
): SafeParseResult<PaginatedResponseAuditControlComment, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      PaginatedResponseAuditControlComment$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PaginatedResponseAuditControlComment' from JSON`,
  );
}
