/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  InformationRequestActivityLog,
  InformationRequestActivityLog$inboundSchema,
} from "./informationrequestactivitylog.js";
import { PageInfo, PageInfo$inboundSchema } from "./pageinfo.js";

export type PaginatedResponseInformationRequestActivityLogResults = {
  data: Array<InformationRequestActivityLog>;
  /**
   * Provides information about the pagination of a dataset.
   */
  pageInfo: PageInfo;
};

export type PaginatedResponseInformationRequestActivityLog = {
  results: PaginatedResponseInformationRequestActivityLogResults;
};

/** @internal */
export const PaginatedResponseInformationRequestActivityLogResults$inboundSchema:
  z.ZodType<
    PaginatedResponseInformationRequestActivityLogResults,
    z.ZodTypeDef,
    unknown
  > = z.object({
    data: z.array(InformationRequestActivityLog$inboundSchema),
    pageInfo: PageInfo$inboundSchema,
  });

export function paginatedResponseInformationRequestActivityLogResultsFromJSON(
  jsonString: string,
): SafeParseResult<
  PaginatedResponseInformationRequestActivityLogResults,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      PaginatedResponseInformationRequestActivityLogResults$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'PaginatedResponseInformationRequestActivityLogResults' from JSON`,
  );
}

/** @internal */
export const PaginatedResponseInformationRequestActivityLog$inboundSchema:
  z.ZodType<
    PaginatedResponseInformationRequestActivityLog,
    z.ZodTypeDef,
    unknown
  > = z.object({
    results: z.lazy(() =>
      PaginatedResponseInformationRequestActivityLogResults$inboundSchema
    ),
  });

export function paginatedResponseInformationRequestActivityLogFromJSON(
  jsonString: string,
): SafeParseResult<
  PaginatedResponseInformationRequestActivityLog,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      PaginatedResponseInformationRequestActivityLog$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'PaginatedResponseInformationRequestActivityLog' from JSON`,
  );
}
