/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import { PageInfo, PageInfo$inboundSchema } from "./pageinfo.js";
import {
  PersonnelGroup,
  PersonnelGroup$inboundSchema,
} from "./personnelgroup.js";

export type PaginatedResponsePersonnelGroupResults = {
  data: Array<PersonnelGroup>;
  /**
   * Provides information about the pagination of a dataset.
   */
  pageInfo: PageInfo;
};

export type PaginatedResponsePersonnelGroup = {
  results: PaginatedResponsePersonnelGroupResults;
};

/** @internal */
export const PaginatedResponsePersonnelGroupResults$inboundSchema: z.ZodType<
  PaginatedResponsePersonnelGroupResults,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: z.array(PersonnelGroup$inboundSchema),
  pageInfo: PageInfo$inboundSchema,
});

export function paginatedResponsePersonnelGroupResultsFromJSON(
  jsonString: string,
): SafeParseResult<PaginatedResponsePersonnelGroupResults, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      PaginatedResponsePersonnelGroupResults$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PaginatedResponsePersonnelGroupResults' from JSON`,
  );
}

/** @internal */
export const PaginatedResponsePersonnelGroup$inboundSchema: z.ZodType<
  PaginatedResponsePersonnelGroup,
  z.ZodTypeDef,
  unknown
> = z.object({
  results: z.lazy(() => PaginatedResponsePersonnelGroupResults$inboundSchema),
});

export function paginatedResponsePersonnelGroupFromJSON(
  jsonString: string,
): SafeParseResult<PaginatedResponsePersonnelGroup, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PaginatedResponsePersonnelGroup$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PaginatedResponsePersonnelGroup' from JSON`,
  );
}
