/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  InformationRequestComment,
  InformationRequestComment$inboundSchema,
} from "./informationrequestcomment.js";
import { PageInfo, PageInfo$inboundSchema } from "./pageinfo.js";

export type PaginatedResponseInformationRequestCommentResults = {
  data: Array<InformationRequestComment>;
  /**
   * Provides information about the pagination of a dataset.
   */
  pageInfo: PageInfo;
};

export type PaginatedResponseInformationRequestComment = {
  results: PaginatedResponseInformationRequestCommentResults;
};

/** @internal */
export const PaginatedResponseInformationRequestCommentResults$inboundSchema:
  z.ZodType<
    PaginatedResponseInformationRequestCommentResults,
    z.ZodTypeDef,
    unknown
  > = z.object({
    data: z.array(InformationRequestComment$inboundSchema),
    pageInfo: PageInfo$inboundSchema,
  });

export function paginatedResponseInformationRequestCommentResultsFromJSON(
  jsonString: string,
): SafeParseResult<
  PaginatedResponseInformationRequestCommentResults,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      PaginatedResponseInformationRequestCommentResults$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'PaginatedResponseInformationRequestCommentResults' from JSON`,
  );
}

/** @internal */
export const PaginatedResponseInformationRequestComment$inboundSchema:
  z.ZodType<PaginatedResponseInformationRequestComment, z.ZodTypeDef, unknown> =
    z.object({
      results: z.lazy(() =>
        PaginatedResponseInformationRequestCommentResults$inboundSchema
      ),
    });

export function paginatedResponseInformationRequestCommentFromJSON(
  jsonString: string,
): SafeParseResult<
  PaginatedResponseInformationRequestComment,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      PaginatedResponseInformationRequestComment$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'PaginatedResponseInformationRequestComment' from JSON`,
  );
}
