/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  InformationRequestEvidence,
  InformationRequestEvidence$inboundSchema,
} from "./informationrequestevidence.js";
import { PageInfo, PageInfo$inboundSchema } from "./pageinfo.js";

export type PaginatedResponseInformationRequestEvidenceResults = {
  data: Array<InformationRequestEvidence>;
  /**
   * Provides information about the pagination of a dataset.
   */
  pageInfo: PageInfo;
};

export type PaginatedResponseInformationRequestEvidence = {
  results: PaginatedResponseInformationRequestEvidenceResults;
};

/** @internal */
export const PaginatedResponseInformationRequestEvidenceResults$inboundSchema:
  z.ZodType<
    PaginatedResponseInformationRequestEvidenceResults,
    z.ZodTypeDef,
    unknown
  > = z.object({
    data: z.array(InformationRequestEvidence$inboundSchema),
    pageInfo: PageInfo$inboundSchema,
  });

export function paginatedResponseInformationRequestEvidenceResultsFromJSON(
  jsonString: string,
): SafeParseResult<
  PaginatedResponseInformationRequestEvidenceResults,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      PaginatedResponseInformationRequestEvidenceResults$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'PaginatedResponseInformationRequestEvidenceResults' from JSON`,
  );
}

/** @internal */
export const PaginatedResponseInformationRequestEvidence$inboundSchema:
  z.ZodType<
    PaginatedResponseInformationRequestEvidence,
    z.ZodTypeDef,
    unknown
  > = z.object({
    results: z.lazy(() =>
      PaginatedResponseInformationRequestEvidenceResults$inboundSchema
    ),
  });

export function paginatedResponseInformationRequestEvidenceFromJSON(
  jsonString: string,
): SafeParseResult<
  PaginatedResponseInformationRequestEvidence,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      PaginatedResponseInformationRequestEvidence$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'PaginatedResponseInformationRequestEvidence' from JSON`,
  );
}
