/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import { AuditRisk, AuditRisk$inboundSchema } from "./auditrisk.js";
import { PageInfo, PageInfo$inboundSchema } from "./pageinfo.js";

export type PaginatedResponseAuditRiskResults = {
  data: Array<AuditRisk>;
  /**
   * Provides information about the pagination of a dataset.
   */
  pageInfo: PageInfo;
};

export type PaginatedResponseAuditRisk = {
  results: PaginatedResponseAuditRiskResults;
};

/** @internal */
export const PaginatedResponseAuditRiskResults$inboundSchema: z.ZodType<
  PaginatedResponseAuditRiskResults,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: z.array(AuditRisk$inboundSchema),
  pageInfo: PageInfo$inboundSchema,
});

export function paginatedResponseAuditRiskResultsFromJSON(
  jsonString: string,
): SafeParseResult<PaginatedResponseAuditRiskResults, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PaginatedResponseAuditRiskResults$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PaginatedResponseAuditRiskResults' from JSON`,
  );
}

/** @internal */
export const PaginatedResponseAuditRisk$inboundSchema: z.ZodType<
  PaginatedResponseAuditRisk,
  z.ZodTypeDef,
  unknown
> = z.object({
  results: z.lazy(() => PaginatedResponseAuditRiskResults$inboundSchema),
});

export function paginatedResponseAuditRiskFromJSON(
  jsonString: string,
): SafeParseResult<PaginatedResponseAuditRisk, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PaginatedResponseAuditRisk$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PaginatedResponseAuditRisk' from JSON`,
  );
}
