/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import {
  InformationRequestCadence,
  InformationRequestCadence$outboundSchema,
} from "./informationrequestcadence.js";
import {
  InformationRequestType,
  InformationRequestType$outboundSchema,
} from "./informationrequesttype.js";

/**
 * Input for partially updating an information request. Only provided fields
 *
 * @remarks
 * will be updated; omitted fields remain unchanged. At least one field must
 * be provided.
 */
export type PartialUpdateInformationRequest = {
  /**
   * The framework codes this request addresses.
   *
   * @remarks
   * An empty array if no framework codes are associated.
   */
  frameworkCodes?: Array<string> | undefined;
  /**
   * Detailed description of what evidence is needed.
   */
  description?: string | null | undefined;
  /**
   * Deadline for fulfilling this request. Null if no deadline.
   *
   * @remarks
   * Format: ISO 8601 UTC timestamp.
   */
  dueDate?: Date | null | undefined;
  /**
   * Start date of the audit period. Evidence before this date may not be accepted.
   *
   * @remarks
   * Null if not restricted. Format: ISO 8601 UTC timestamp.
   */
  evidenceCaptureDate?: Date | null | undefined;
  /**
   * Type of information request, defining what scope of evidence is needed.
   *
   * @remarks
   *
   * - POINT_IN_TIME: Evidence for a specific moment (e.g., current state of a policy)
   * - POPULATION: Evidence covering all items in a category (e.g., all employees)
   * - SAMPLE: Evidence for a representative sample (e.g., 10 random customer records)
   */
  requestType?: InformationRequestType | undefined;
  /**
   * Short, descriptive title.
   */
  title?: string | undefined;
  /**
   * Frequency cadence for the information request, indicating how often it recurs.
   */
  cadence?: InformationRequestCadence | undefined;
};

/** @internal */
export type PartialUpdateInformationRequest$Outbound = {
  frameworkCodes?: Array<string> | undefined;
  description?: string | null | undefined;
  dueDate?: string | null | undefined;
  evidenceCaptureDate?: string | null | undefined;
  requestType?: string | undefined;
  title?: string | undefined;
  cadence?: string | undefined;
};

/** @internal */
export const PartialUpdateInformationRequest$outboundSchema: z.ZodType<
  PartialUpdateInformationRequest$Outbound,
  z.ZodTypeDef,
  PartialUpdateInformationRequest
> = z.object({
  frameworkCodes: z.array(z.string()).optional(),
  description: z.nullable(z.string()).optional(),
  dueDate: z.nullable(z.date().transform(v => v.toISOString())).optional(),
  evidenceCaptureDate: z.nullable(z.date().transform(v => v.toISOString()))
    .optional(),
  requestType: InformationRequestType$outboundSchema.optional(),
  title: z.string().optional(),
  cadence: InformationRequestCadence$outboundSchema.optional(),
});

export function partialUpdateInformationRequestToJSON(
  partialUpdateInformationRequest: PartialUpdateInformationRequest,
): string {
  return JSON.stringify(
    PartialUpdateInformationRequest$outboundSchema.parse(
      partialUpdateInformationRequest,
    ),
  );
}
