/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { ClosedEnum } from "../../types/enums.js";

/**
 * Employment status filter for people queries.
 */
export const PeopleEmploymentStatus = {
  CurrentlyEmployed: "CURRENTLY_EMPLOYED",
  InactiveEmployee: "INACTIVE_EMPLOYEE",
  NotPeople: "NOT_PEOPLE",
  OnLeave: "ON_LEAVE",
  PreviouslyEmployed: "PREVIOUSLY_EMPLOYED",
  UpcomingEmployee: "UPCOMING_EMPLOYEE",
} as const;
/**
 * Employment status filter for people queries.
 */
export type PeopleEmploymentStatus = ClosedEnum<typeof PeopleEmploymentStatus>;

/** @internal */
export const PeopleEmploymentStatus$outboundSchema: z.ZodNativeEnum<
  typeof PeopleEmploymentStatus
> = z.nativeEnum(PeopleEmploymentStatus);
