/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { ClosedEnum } from "../../types/enums.js";

/**
 * Security task status for individual task categories.
 */
export const PeopleSecurityTaskStatus = {
  NoSecurityTasks: "NO_SECURITY_TASKS",
  SecurityTasksComplete: "SECURITY_TASKS_COMPLETE",
  SecurityTasksDueSoon: "SECURITY_TASKS_DUE_SOON",
  SecurityTasksOverdue: "SECURITY_TASKS_OVERDUE",
} as const;
/**
 * Security task status for individual task categories.
 */
export type PeopleSecurityTaskStatus = ClosedEnum<
  typeof PeopleSecurityTaskStatus
>;

/** @internal */
export const PeopleSecurityTaskStatus$inboundSchema: z.ZodNativeEnum<
  typeof PeopleSecurityTaskStatus
> = z.nativeEnum(PeopleSecurityTaskStatus);
