/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * A task assigned to a personnel group.
 */
export type PersonnelGroupTask = {
  /**
   * Task name
   */
  name: string;
};

/** @internal */
export const PersonnelGroupTask$inboundSchema: z.ZodType<
  PersonnelGroupTask,
  z.ZodTypeDef,
  unknown
> = z.object({
  name: z.string(),
});

export function personnelGroupTaskFromJSON(
  jsonString: string,
): SafeParseResult<PersonnelGroupTask, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PersonnelGroupTask$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PersonnelGroupTask' from JSON`,
  );
}
