/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { ClosedEnum } from "../../types/enums.js";

export const RecurrenceDuration = {
  P0D: "P0D",
  P1D: "P1D",
  P1W: "P1W",
  P1M: "P1M",
  P3M: "P3M",
  P6M: "P6M",
  P1Y: "P1Y",
} as const;
export type RecurrenceDuration = ClosedEnum<typeof RecurrenceDuration>;

/** @internal */
export const RecurrenceDuration$inboundSchema: z.ZodNativeEnum<
  typeof RecurrenceDuration
> = z.nativeEnum(RecurrenceDuration);
/** @internal */
export const RecurrenceDuration$outboundSchema: z.ZodNativeEnum<
  typeof RecurrenceDuration
> = RecurrenceDuration$inboundSchema;
