/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { ClosedEnum } from "../../types/enums.js";

export const RiskOrderBy = {
  InherentRisk: "inherentRisk",
  RiskId: "riskId",
  RiskScenario: "riskScenario",
  Treatment: "treatment",
  ResidualRisk: "residualRisk",
  ReviewStatus: "reviewStatus",
  Owner: "owner",
  Categories: "categories",
  CiaCategories: "ciaCategories",
  Identified: "identified",
} as const;
export type RiskOrderBy = ClosedEnum<typeof RiskOrderBy>;

/** @internal */
export const RiskOrderBy$outboundSchema: z.ZodNativeEnum<typeof RiskOrderBy> = z
  .nativeEnum(RiskOrderBy);
