/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * The person's information comes from SCIM.
 */
export type ScimBasedPersonInfoSource = {
  type: "SCIM";
};

/** @internal */
export const ScimBasedPersonInfoSource$inboundSchema: z.ZodType<
  ScimBasedPersonInfoSource,
  z.ZodTypeDef,
  unknown
> = z.object({
  type: z.literal("SCIM"),
});

export function scimBasedPersonInfoSourceFromJSON(
  jsonString: string,
): SafeParseResult<ScimBasedPersonInfoSource, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ScimBasedPersonInfoSource$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ScimBasedPersonInfoSource' from JSON`,
  );
}
