/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type Section = {
  /**
   * The section name
   */
  name: string;
  /**
   * The section framework
   */
  framework: string;
};

/** @internal */
export const Section$inboundSchema: z.ZodType<Section, z.ZodTypeDef, unknown> =
  z.object({
    name: z.string(),
    framework: z.string(),
  });

export function sectionFromJSON(
  jsonString: string,
): SafeParseResult<Section, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Section$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Section' from JSON`,
  );
}
