/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { ClosedEnum } from "../../types/enums.js";

/**
 * The status of a task.
 *
 * @remarks
 * - COMPLETE: The task has been completed.
 * - DUE_SOON: The task is due soon.
 * - OVERDUE: The task is overdue.
 * - NONE: The task is not assigned.
 */
export const TaskStatus = {
  Complete: "COMPLETE",
  DueSoon: "DUE_SOON",
  Overdue: "OVERDUE",
  None: "NONE",
} as const;
/**
 * The status of a task.
 *
 * @remarks
 * - COMPLETE: The task has been completed.
 * - DUE_SOON: The task is due soon.
 * - OVERDUE: The task is overdue.
 * - NONE: The task is not assigned.
 */
export type TaskStatus = ClosedEnum<typeof TaskStatus>;

/** @internal */
export const TaskStatus$inboundSchema: z.ZodNativeEnum<typeof TaskStatus> = z
  .nativeEnum(TaskStatus);
/** @internal */
export const TaskStatus$outboundSchema: z.ZodNativeEnum<typeof TaskStatus> =
  TaskStatus$inboundSchema;
