/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { ClosedEnum } from "../../types/enums.js";

export const TaskTypeCOMPLETEBACKGROUNDCHECKS = {
  CompleteBackgroundChecks: "COMPLETE_BACKGROUND_CHECKS",
} as const;
export type TaskTypeCOMPLETEBACKGROUNDCHECKS = ClosedEnum<
  typeof TaskTypeCOMPLETEBACKGROUNDCHECKS
>;

/** @internal */
export const TaskTypeCOMPLETEBACKGROUNDCHECKS$inboundSchema: z.ZodNativeEnum<
  typeof TaskTypeCOMPLETEBACKGROUNDCHECKS
> = z.nativeEnum(TaskTypeCOMPLETEBACKGROUNDCHECKS);
