/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  AcceptPoliciesTaskSummary,
  AcceptPoliciesTaskSummary$inboundSchema,
} from "./acceptpoliciestasksummary.js";
import {
  CompleteBackgroundChecksTaskSummary,
  CompleteBackgroundChecksTaskSummary$inboundSchema,
} from "./completebackgroundcheckstasksummary.js";
import {
  CompleteCustomTasksTaskSummary,
  CompleteCustomTasksTaskSummary$inboundSchema,
} from "./completecustomtaskstasksummary.js";
import {
  CompleteOffboardingCustomTasksTaskSummary,
  CompleteOffboardingCustomTasksTaskSummary$inboundSchema,
} from "./completeoffboardingcustomtaskstasksummary.js";
import {
  CompleteTrainingsTaskSummary,
  CompleteTrainingsTaskSummary$inboundSchema,
} from "./completetrainingstasksummary.js";
import {
  InstallDeviceMonitoringTaskSummary,
  InstallDeviceMonitoringTaskSummary$inboundSchema,
} from "./installdevicemonitoringtasksummary.js";

/**
 * All detailed information about a person's tasks, split across task categories.
 */
export type TaskSummaryDetails = {
  /**
   * Task summary for completing all trainings.
   */
  completeTrainings: CompleteTrainingsTaskSummary;
  /**
   * Policy acceptance details for a person.
   */
  acceptPolicies: AcceptPoliciesTaskSummary;
  /**
   * Task summary for completing all custom tasks.
   */
  completeCustomTasks: CompleteCustomTasksTaskSummary;
  /**
   * Task summary for completing all offboarding custom tasks.
   */
  completeOffboardingCustomTasks: CompleteOffboardingCustomTasksTaskSummary;
  /**
   * Task summary for installing device monitoring.
   */
  installDeviceMonitoring: InstallDeviceMonitoringTaskSummary;
  /**
   * Task summary for completing background checks.
   */
  completeBackgroundChecks: CompleteBackgroundChecksTaskSummary;
};

/** @internal */
export const TaskSummaryDetails$inboundSchema: z.ZodType<
  TaskSummaryDetails,
  z.ZodTypeDef,
  unknown
> = z.object({
  completeTrainings: CompleteTrainingsTaskSummary$inboundSchema,
  acceptPolicies: AcceptPoliciesTaskSummary$inboundSchema,
  completeCustomTasks: CompleteCustomTasksTaskSummary$inboundSchema,
  completeOffboardingCustomTasks:
    CompleteOffboardingCustomTasksTaskSummary$inboundSchema,
  installDeviceMonitoring: InstallDeviceMonitoringTaskSummary$inboundSchema,
  completeBackgroundChecks: CompleteBackgroundChecksTaskSummary$inboundSchema,
});

export function taskSummaryDetailsFromJSON(
  jsonString: string,
): SafeParseResult<TaskSummaryDetails, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => TaskSummaryDetails$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'TaskSummaryDetails' from JSON`,
  );
}
