/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

/**
 * Updates an existing comment on an information request.
 *
 * @remarks
 * Only the original author of the comment can update it.
 */
export type UpdateInformationRequestCommentInput = {
  /**
   * The text content of the comment.
   *
   * @remarks
   * Must be at least 1 character. Can include questions, clarifications,
   * or explanations related to the information request.
   */
  text: string;
  /**
   * Email address of the comment author.
   *
   * @remarks
   * Must match an existing Vanta user who belongs to the audit firm making the API request.
   * This email uniquely identifies the author across systems.
   */
  email: string;
};

/** @internal */
export type UpdateInformationRequestCommentInput$Outbound = {
  text: string;
  email: string;
};

/** @internal */
export const UpdateInformationRequestCommentInput$outboundSchema: z.ZodType<
  UpdateInformationRequestCommentInput$Outbound,
  z.ZodTypeDef,
  UpdateInformationRequestCommentInput
> = z.object({
  text: z.string(),
  email: z.string(),
});

export function updateInformationRequestCommentInputToJSON(
  updateInformationRequestCommentInput: UpdateInformationRequestCommentInput,
): string {
  return JSON.stringify(
    UpdateInformationRequestCommentInput$outboundSchema.parse(
      updateInformationRequestCommentInput,
    ),
  );
}
