/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

/**
 * Updates an existing comment on a control.
 *
 * @remarks
 * Only the original author of the comment can update it.
 */
export type UpdateAuditControlCommentInput = {
  /**
   * The text content of the comment.
   *
   * @remarks
   * Must be at least 1 character. Can include questions, clarifications,
   * or explanations related to the control.
   */
  text: string;
  /**
   * Email address of the comment author.
   *
   * @remarks
   * Must match an existing Vanta user who belongs to the audit firm making the API request.
   * This email uniquely identifies the author across systems.
   */
  email: string;
};

/** @internal */
export type UpdateAuditControlCommentInput$Outbound = {
  text: string;
  email: string;
};

/** @internal */
export const UpdateAuditControlCommentInput$outboundSchema: z.ZodType<
  UpdateAuditControlCommentInput$Outbound,
  z.ZodTypeDef,
  UpdateAuditControlCommentInput
> = z.object({
  text: z.string(),
  email: z.string(),
});

export function updateAuditControlCommentInputToJSON(
  updateAuditControlCommentInput: UpdateAuditControlCommentInput,
): string {
  return JSON.stringify(
    UpdateAuditControlCommentInput$outboundSchema.parse(
      updateAuditControlCommentInput,
    ),
  );
}
