/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import {
  AuditControlAssessmentState,
  AuditControlAssessmentState$outboundSchema,
} from "./auditcontrolassessmentstate.js";

/**
 * Input for upserting a control's auditor assessment within an audit. Overwrites
 *
 * @remarks
 * the assessment for this control in the chosen program segment.
 */
export type UpsertAuditControlAssessmentInput = {
  /**
   * The program segment to assess. Required when the audit has more than one
   *
   * @remarks
   * program segment. Optional on a single-program audit (the only program is
   * used). Must be a program segment on the audit; system segments are rejected.
   */
  segmentId?: string | undefined;
  /**
   * An auditor's assessment of a control within an audit. This is the full flat
   *
   * @remarks
   * union of every framework's assessment states (the superset); a given audit's
   * framework only uses its own subset. `NOT_ASSESSED` is shared by all
   * frameworks and is the default for a control that has not yet been assessed.
   *
   * Which states apply to which framework:
   * - Most frameworks (e.g. SOC 2): `IN_PLACE`, `NOT_IN_PLACE`, `PARTIAL`, `NOT_ASSESSED`
   * - ISO 27001: `CONFORMING`, `MINOR_NON_CONFORMITY`, `MAJOR_NON_CONFORMITY`, `NOT_ASSESSED`
   * - FedRAMP: `SATISFIED`, `NOT_SATISFIED`, `OTHER_THAN_SATISFIED`, `NOT_ASSESSED`
   * - FedRAMP Key Security Indicators (KSI): `TRUE`, `FALSE`, `PARTIAL`, `NOT_ASSESSED`
   *
   * Distinct from `ControlStatus`, which is the computed tests/documents-passing
   * status — a different concept.
   */
  assessmentState: AuditControlAssessmentState;
  /**
   * Free-text reasoning for the assessment. Required, and at most 5000 characters.
   */
  justification: string;
  /**
   * Email of the auditor performing the assessment. Must match an existing Vanta
   *
   * @remarks
   * user who belongs to the audit firm making the API request.
   */
  auditorEmail: string;
};

/** @internal */
export type UpsertAuditControlAssessmentInput$Outbound = {
  segmentId?: string | undefined;
  assessmentState: string;
  justification: string;
  auditorEmail: string;
};

/** @internal */
export const UpsertAuditControlAssessmentInput$outboundSchema: z.ZodType<
  UpsertAuditControlAssessmentInput$Outbound,
  z.ZodTypeDef,
  UpsertAuditControlAssessmentInput
> = z.object({
  segmentId: z.string().optional(),
  assessmentState: AuditControlAssessmentState$outboundSchema,
  justification: z.string(),
  auditorEmail: z.string(),
});

export function upsertAuditControlAssessmentInputToJSON(
  upsertAuditControlAssessmentInput: UpsertAuditControlAssessmentInput,
): string {
  return JSON.stringify(
    UpsertAuditControlAssessmentInput$outboundSchema.parse(
      upsertAuditControlAssessmentInput,
    ),
  );
}
