/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * The person's information comes from what is set in Vanta.
 */
export type VantaBasedPersonInfoSource = {
  type: "VANTA";
};

/** @internal */
export const VantaBasedPersonInfoSource$inboundSchema: z.ZodType<
  VantaBasedPersonInfoSource,
  z.ZodTypeDef,
  unknown
> = z.object({
  type: z.literal("VANTA"),
});

export function vantaBasedPersonInfoSourceFromJSON(
  jsonString: string,
): SafeParseResult<VantaBasedPersonInfoSource, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => VantaBasedPersonInfoSource$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'VantaBasedPersonInfoSource' from JSON`,
  );
}
