/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * Represents an external link in a Vanta Document.
 *
 * @remarks
 * The link points to documentation hosted outside of Vanta's system.
 */
export type VantaDocumentLinkEvidence = {
  /**
   * Discriminator to identify this as an external link.
   */
  type: "link";
  /**
   * The unique identifier for the file version in Vanta's system.
   */
  id: string;
  /**
   * The URL pointing to the external documentation or resource.
   */
  url: string;
};

/** @internal */
export const VantaDocumentLinkEvidence$inboundSchema: z.ZodType<
  VantaDocumentLinkEvidence,
  z.ZodTypeDef,
  unknown
> = z.object({
  type: z.literal("link"),
  id: z.string(),
  url: z.string(),
});

export function vantaDocumentLinkEvidenceFromJSON(
  jsonString: string,
): SafeParseResult<VantaDocumentLinkEvidence, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => VantaDocumentLinkEvidence$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'VantaDocumentLinkEvidence' from JSON`,
  );
}
