/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * Integration metadata for a test, mirroring the Vanta web app.
 */
export type VantaTestSnapshotIntegration = {
  integrationId: string;
  displayName: string;
};

/** @internal */
export const VantaTestSnapshotIntegration$inboundSchema: z.ZodType<
  VantaTestSnapshotIntegration,
  z.ZodTypeDef,
  unknown
> = z.object({
  integrationId: z.string(),
  displayName: z.string(),
});

export function vantaTestSnapshotIntegrationFromJSON(
  jsonString: string,
): SafeParseResult<VantaTestSnapshotIntegration, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => VantaTestSnapshotIntegration$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'VantaTestSnapshotIntegration' from JSON`,
  );
}
