/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  VantaTestSnapshotExcludedItemGroup,
  VantaTestSnapshotExcludedItemGroup$inboundSchema,
} from "./vantatestsnapshotexcludeditemgroup.js";

export type VantaTestSnapshotFrameworkExclusion = {
  frameworkId: string;
  frameworkName: string;
  groupedByReason: Array<VantaTestSnapshotExcludedItemGroup>;
};

/** @internal */
export const VantaTestSnapshotFrameworkExclusion$inboundSchema: z.ZodType<
  VantaTestSnapshotFrameworkExclusion,
  z.ZodTypeDef,
  unknown
> = z.object({
  frameworkId: z.string(),
  frameworkName: z.string(),
  groupedByReason: z.array(VantaTestSnapshotExcludedItemGroup$inboundSchema),
});

export function vantaTestSnapshotFrameworkExclusionFromJSON(
  jsonString: string,
): SafeParseResult<VantaTestSnapshotFrameworkExclusion, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      VantaTestSnapshotFrameworkExclusion$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'VantaTestSnapshotFrameworkExclusion' from JSON`,
  );
}
