/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type VantaTestSnapshotExcludedItem = {
  id: string;
  displayName: string | null;
};

/** @internal */
export const VantaTestSnapshotExcludedItem$inboundSchema: z.ZodType<
  VantaTestSnapshotExcludedItem,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
  displayName: z.nullable(z.string()),
});

export function vantaTestSnapshotExcludedItemFromJSON(
  jsonString: string,
): SafeParseResult<VantaTestSnapshotExcludedItem, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => VantaTestSnapshotExcludedItem$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'VantaTestSnapshotExcludedItem' from JSON`,
  );
}
