/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { ClosedEnum } from "../../types/enums.js";

export const VantaTestFileType = {
  TestEvidenceWorkpaper: "TEST_EVIDENCE_WORKPAPER",
  TestRawData: "TEST_RAW_DATA",
  OutOfScopeResources: "OUT_OF_SCOPE_RESOURCES",
  ApiRequests: "API_REQUESTS",
} as const;
export type VantaTestFileType = ClosedEnum<typeof VantaTestFileType>;

/** @internal */
export const VantaTestFileType$inboundSchema: z.ZodNativeEnum<
  typeof VantaTestFileType
> = z.nativeEnum(VantaTestFileType);
