/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { ClosedEnum } from "../../types/enums.js";

export const VendorDecisionStatus = {
  Approved: "APPROVED",
  ConditionallyApproved: "CONDITIONALLY_APPROVED",
  NotApproved: "NOT_APPROVED",
} as const;
export type VendorDecisionStatus = ClosedEnum<typeof VendorDecisionStatus>;

/** @internal */
export const VendorDecisionStatus$inboundSchema: z.ZodNativeEnum<
  typeof VendorDecisionStatus
> = z.nativeEnum(VendorDecisionStatus);
