/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { ClosedEnum } from "../../types/enums.js";

export const VendorOrderBy = {
  Name: "name",
  InherentRisk: "inherentRisk",
} as const;
export type VendorOrderBy = ClosedEnum<typeof VendorOrderBy>;

/** @internal */
export const VendorOrderBy$outboundSchema: z.ZodNativeEnum<
  typeof VendorOrderBy
> = z.nativeEnum(VendorOrderBy);
